import { TRPCError } from "@trpc/server";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { opportunities, salesCampaigns, salesCommissions, salesGoals, users } from "../../drizzle/schema";
import { getDb, recordAudit } from "../db";
import { calculateCommission } from "../commissionDomain";
import { calculateCampaignProgress } from "../campaignProgress";
import { borderoSummary, type CommissionStatus } from "../commissionLifecycle";
import { router } from "../_core/trpc";
import { adminProcedure, commissionsProcedure, financeProcedure } from "./access";

const campaignInput = z.object({ name: z.string().min(3).max(180), code: z.string().min(2).max(64).transform(value => value.trim().toUpperCase().replace(/\s+/g, "-")), description: z.string().max(2000).optional(), startsAt: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(), endsAt: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(), commissionRate: z.coerce.number().min(0).max(100), targetAmount: z.coerce.number().min(0).default(0), status: z.enum(["draft", "active", "closed"]).default("draft") });

export const commissionsRouter = router({
  overview: commissionsProcedure.input(z.object({ campaignId: z.number().int().positive().optional(), sellerId: z.number().int().positive().optional() }).optional()).query(async ({ ctx, input }) => {
    const db = await getDb(); if (!db) return { campaigns: [], ranking: [], entries: [] };
    const sellerId = ctx.user.role === "seller" ? ctx.user.id : input?.sellerId;
    const [campaigns, opportunityRows, commissionRows, sellerRows, goalRows] = await Promise.all([
      db.select().from(salesCampaigns),
      db.select({ opportunity: opportunities, sellerName: users.name, sellerEmail: users.email, campaignName: salesCampaigns.name, campaignCode: salesCampaigns.code }).from(opportunities).leftJoin(users, eq(opportunities.sellerId, users.id)).leftJoin(salesCampaigns, eq(opportunities.campaignId, salesCampaigns.id)),
      db.select({ commission: salesCommissions, sellerName: users.name, campaignName: salesCampaigns.name, campaignCode: salesCampaigns.code }).from(salesCommissions).leftJoin(users, eq(salesCommissions.sellerId, users.id)).leftJoin(salesCampaigns, eq(salesCommissions.campaignId, salesCampaigns.id)),
      db.select({ id: users.id, name: users.name, email: users.email }).from(users).where(eq(users.role, "seller")),
      db.select().from(salesGoals),
    ]);
    const selectedOpportunities = opportunityRows.filter(row => row.opportunity.stage === "won" && (!input?.campaignId || row.opportunity.campaignId === input.campaignId) && (!sellerId || row.opportunity.sellerId === sellerId));
    const selectedCommissions = commissionRows.filter(row => (!input?.campaignId || row.commission.campaignId === input.campaignId) && (!sellerId || row.commission.sellerId === sellerId));
    const rank = new Map<number, { sellerId: number; sellerName: string; salesAmount: number; wonCount: number; commissionAmount: number; pendingAmount: number; paidAmount: number }>();
    selectedOpportunities.forEach(row => { if (!row.opportunity.sellerId) return; const item = rank.get(row.opportunity.sellerId) ?? { sellerId: row.opportunity.sellerId, sellerName: row.sellerName || row.sellerEmail || "Sem vendedor", salesAmount: 0, wonCount: 0, commissionAmount: 0, pendingAmount: 0, paidAmount: 0 }; item.salesAmount += Number(row.opportunity.expectedAmount); item.wonCount += 1; rank.set(item.sellerId, item); });
    selectedCommissions.forEach(row => { const item = rank.get(row.commission.sellerId) ?? { sellerId: row.commission.sellerId, sellerName: row.sellerName || "Vendedor", salesAmount: 0, wonCount: 0, commissionAmount: 0, pendingAmount: 0, paidAmount: 0 }; const value = Number(row.commission.amount); if (row.commission.status !== "cancelled") item.commissionAmount += value; if (row.commission.status === "pending" || row.commission.status === "approved") item.pendingAmount += value; if (row.commission.status === "paid") item.paidAmount += value; rank.set(item.sellerId, item); });
    const ranking = Array.from(rank.values()).sort((a, b) => b.salesAmount - a.salesAmount).map((item, index) => ({ ...item, position: index + 1 }));
    const entries = selectedCommissions.sort((a, b) => b.commission.createdAt.getTime() - a.commission.createdAt.getTime()); const bordero = borderoSummary(entries.map(row => ({ amount: Number(row.commission.amount), expectedPaymentAt: row.commission.expectedPaymentAt ?? row.commission.createdAt, status: (row.commission.status === "paid" ? "paid" : row.commission.status === "cancelled" ? "cancelled" : row.commission.lifecycleStatus) as CommissionStatus })));
    return { campaigns: campaigns.map(campaign => { const salesAmount = selectedOpportunities.filter(item => item.opportunity.campaignId === campaign.id).reduce((sum, item) => sum + Number(item.opportunity.expectedAmount), 0); return { ...campaign, ...calculateCampaignProgress(Number(campaign.targetAmount), salesAmount) }; }), sellers: sellerRows.map(item => ({ id: item.id, name: item.name || item.email || "Vendedor" })), ranking, goals: goalRows.map(goal => { const currentAmount = ranking.find(item => item.sellerId === goal.sellerId)?.salesAmount ?? 0; return { sellerId: goal.sellerId, targetAmount: Number(goal.targetAmount), currentAmount, progress: Number(goal.targetAmount) ? Math.min(100, currentAmount / Number(goal.targetAmount) * 100) : 0 }; }), entries, bordero };
  }),
  createCampaign: adminProcedure.input(campaignInput).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível." }); const created = await db.insert(salesCampaigns).values({ ...input, startsAt: input.startsAt ? new Date(`${input.startsAt}T12:00:00Z`) : null, endsAt: input.endsAt ? new Date(`${input.endsAt}T12:00:00Z`) : null, commissionRate: input.commissionRate.toFixed(2), targetAmount: input.targetAmount.toFixed(2) }).$returningId(); const id = created[0]?.id; if (!id) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Não foi possível criar a campanha." }); await recordAudit(ctx.user.id, "sales_campaign", id, "created", `Campanha ${input.code} criada com meta de R$ ${input.targetAmount.toFixed(2)} e comissão de ${input.commissionRate}%.`); return { id }; }),
  record: financeProcedure.input(z.object({ sellerId: z.number().int().positive(), campaignId: z.number().int().positive().optional(), opportunityId: z.number().int().positive().optional(), baseAmount: z.coerce.number().positive(), rate: z.coerce.number().min(0).max(100), notes: z.string().max(2000).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível." }); const amount = calculateCommission(input.baseAmount, input.rate); const created = await db.insert(salesCommissions).values({ sellerId: input.sellerId, campaignId: input.campaignId ?? null, opportunityId: input.opportunityId ?? null, baseAmount: input.baseAmount.toFixed(2), rate: input.rate.toFixed(2), amount: amount.toFixed(2), notes: input.notes ?? null }).$returningId(); const id = created[0]?.id; if (!id) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Não foi possível registrar a comissão." }); await recordAudit(ctx.user.id, "sales_commission", id, "created", `Comissão de ${amount.toFixed(2)} lançada.`); return { id, amount }; }),
  setStatus: financeProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["approved", "paid", "cancelled"]) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco indisponível." }); await db.update(salesCommissions).set({ status: input.status, approvedAt: input.status === "approved" ? new Date() : undefined, paidAt: input.status === "paid" ? new Date() : undefined }).where(eq(salesCommissions.id, input.id)); await recordAudit(ctx.user.id, "sales_commission", input.id, input.status, `Comissão marcada como ${input.status}.`); return { success: true }; }),
});
