import { EmptyState, PageHeader } from "@/components/crm/ui";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { BookOpenCheck, CalendarRange, Megaphone, Plus, Target } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";

const stageOptions = [
  ["new", "Entrada"], ["qualified", "Qualificação"], ["proposal", "Proposta"],
  ["negotiation", "Negociação"], ["won", "Ganho"], ["lost", "Perdido"],
] as const;

const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const dateText = (value: Date | string | null) => value ? new Date(value).toLocaleDateString("pt-BR") : "—";
const monthStart = () => `${new Date().toISOString().slice(0, 7)}-01`;

export default function Campaigns() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const utils = trpc.useUtils();
  const overview = trpc.commissions.overview.useQuery({});
  const goals = trpc.sales.goals.useQuery();
  const playbooks = trpc.sales.playbooks.useQuery();
  const [campaign, setCampaign] = useState({ name: "", code: "", description: "", startsAt: "", endsAt: "", commissionRate: "0", status: "draft" as "draft" | "active" | "closed" });
  const [goal, setGoal] = useState({ sellerId: "", monthReference: monthStart(), targetAmount: "", targetContracts: "0" });
  const [playbook, setPlaybook] = useState({ name: "", stage: "qualified", guidance: "", checklist: "" });
  const createCampaign = trpc.commissions.createCampaign.useMutation({ onSuccess: () => { toast.success("Campanha criada. Agora ela pode entrar no funil e nas comissões."); setCampaign({ name: "", code: "", description: "", startsAt: "", endsAt: "", commissionRate: "0", status: "draft" }); utils.commissions.overview.invalidate(); }, onError: error => toast.error(error.message) });
  const createGoal = trpc.sales.createGoal.useMutation({ onSuccess: () => { toast.success("Meta comercial definida."); setGoal(current => ({ ...current, targetAmount: "", targetContracts: "0" })); utils.sales.goals.invalidate(); utils.commissions.overview.invalidate(); }, onError: error => toast.error(error.message) });
  const createPlaybook = trpc.sales.createPlaybook.useMutation({ onSuccess: () => { toast.success("Playbook criado e liberado para o funil."); setPlaybook({ name: "", stage: "qualified", guidance: "", checklist: "" }); utils.sales.playbooks.invalidate(); }, onError: error => toast.error(error.message) });
  const campaigns = overview.data?.campaigns ?? [];
  const sellers = overview.data?.sellers ?? [];
  const totalSales = useMemo(() => campaigns.reduce((sum, item) => sum + item.salesAmount, 0), [campaigns]);

  const submitCampaign = (event: FormEvent) => { event.preventDefault(); createCampaign.mutate({ name: campaign.name, code: campaign.code, description: campaign.description || undefined, startsAt: campaign.startsAt || undefined, endsAt: campaign.endsAt || undefined, commissionRate: Number(campaign.commissionRate), status: campaign.status }); };
  const submitGoal = (event: FormEvent) => { event.preventDefault(); if (!goal.sellerId) return toast.error("Escolha o vendedor da meta."); createGoal.mutate({ sellerId: Number(goal.sellerId), monthReference: goal.monthReference, targetAmount: Number(goal.targetAmount), targetContracts: Number(goal.targetContracts) }); };
  const submitPlaybook = (event: FormEvent) => { event.preventDefault(); createPlaybook.mutate({ name: playbook.name, stage: playbook.stage as "new" | "qualified" | "proposal" | "negotiation" | "won" | "lost", guidance: playbook.guidance, checklist: playbook.checklist || undefined }); };

  if (!user) return <EmptyState title="Acesso necessário" body="Entre no TGR-CRM para acompanhar campanhas, metas e playbooks." />;
  return <div className="space-y-7">
    <PageHeader eyebrow="Gestão comercial" title="Central de campanhas" description="Aqui campanha deixa de ser campo solto no funil: nasce com código, período, comissão, meta e roteiro de execução." />
    <div className="grid gap-4 md:grid-cols-3">
      <Card className="border-[#e8e1d4] bg-[#1d2b2a] text-white"><CardContent className="p-5"><Megaphone className="h-5 w-5 text-[#e8d092]" /><p className="mt-5 text-xs font-bold uppercase tracking-[.14em] text-white/55">Campanhas cadastradas</p><p className="mt-2 font-serif text-4xl">{campaigns.length}</p><p className="mt-2 text-sm text-white/65">{campaigns.filter(item => item.status === "active").length} em operação</p></CardContent></Card>
      <Card className="border-[#e8e1d4] bg-[#c9a557]"><CardContent className="p-5"><Target className="h-5 w-5 text-[#1d2b2a]" /><p className="mt-5 text-xs font-bold uppercase tracking-[.14em] text-[#53401c]">Vendas vinculadas</p><p className="mt-2 font-serif text-4xl text-[#1d2b2a]">{money(totalSales)}</p><p className="mt-2 text-sm text-[#53401c]">volume ganho por campanha</p></CardContent></Card>
      <Card className="border-[#e8e1d4] bg-[#f6f3eb]"><CardContent className="p-5"><BookOpenCheck className="h-5 w-5 text-[#285043]" /><p className="mt-5 text-xs font-bold uppercase tracking-[.14em] text-[#52615c]">Playbooks ativos</p><p className="mt-2 font-serif text-4xl text-[#1d2b2a]">{playbooks.data?.length ?? 0}</p><p className="mt-2 text-sm text-[#52615c]">roteiros por etapa do funil</p></CardContent></Card>
    </div>

    <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]">
      <Card className="border-[#e8e1d4]"><CardContent className="p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#b18f4b]">Portfólio comercial</p><h2 className="mt-1 font-serif text-2xl text-[#1d2b2a]">Campanhas em operação</h2></div><Badge variant="outline" className="border-[#e3d5bc] text-[#8a6b2d]">{campaigns.filter(item => item.status === "active").length} ativas</Badge></div><div className="mt-6 space-y-3">{campaigns.length ? campaigns.map(item => <div key={item.id} className="grid gap-3 rounded-xl border border-[#ece6da] p-4 md:grid-cols-[1fr_auto_auto]"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-[#1d2b2a]">{item.name}</p><Badge className={item.status === "active" ? "bg-[#e5efe4] text-[#285043]" : item.status === "closed" ? "bg-[#ebe8e1] text-[#52615c]" : "bg-[#f4efe2] text-[#8a6b2d]"}>{item.status === "active" ? "Ativa" : item.status === "closed" ? "Encerrada" : "Rascunho"}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{item.code} · {dateText(item.startsAt)} até {dateText(item.endsAt)}</p></div><div><p className="text-xs text-muted-foreground">Comissão</p><p className="font-semibold text-[#1d2b2a]">{item.commissionRate}%</p></div><div><p className="text-xs text-muted-foreground">Vendas</p><p className="font-semibold text-[#1d2b2a]">{money(item.salesAmount)}</p></div></div>) : <EmptyState title="Nenhuma campanha cadastrada" body="Crie a primeira campanha para ligar funil, meta, comissão e DRE." />}</div></CardContent></Card>
      {isAdmin ? <Card className="border-[#e8e1d4] bg-[#fcfbf7]"><CardContent className="p-6"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#b18f4b]">Administração</p><h2 className="mt-1 font-serif text-2xl text-[#1d2b2a]">Nova campanha</h2><form onSubmit={submitCampaign} className="mt-5 space-y-3"><div className="grid gap-2"><Label>Nome</Label><Input required value={campaign.name} onChange={event => setCampaign(current => ({ ...current, name: event.target.value }))} placeholder="Ex.: Férias de Julho 2026" /></div><div className="grid grid-cols-[1fr_.7fr] gap-3"><div className="grid gap-2"><Label>Código</Label><Input required value={campaign.code} onChange={event => setCampaign(current => ({ ...current, code: event.target.value }))} placeholder="JUL-26" /></div><div className="grid gap-2"><Label>Comissão %</Label><Input required type="number" min="0" max="100" step="0.01" value={campaign.commissionRate} onChange={event => setCampaign(current => ({ ...current, commissionRate: event.target.value }))} /></div></div><div className="grid grid-cols-2 gap-3"><div className="grid gap-2"><Label>Início</Label><Input type="date" value={campaign.startsAt} onChange={event => setCampaign(current => ({ ...current, startsAt: event.target.value }))} /></div><div className="grid gap-2"><Label>Fim</Label><Input type="date" value={campaign.endsAt} onChange={event => setCampaign(current => ({ ...current, endsAt: event.target.value }))} /></div></div><div className="grid gap-2"><Label>Status</Label><Select value={campaign.status} onValueChange={value => setCampaign(current => ({ ...current, status: value as "draft" | "active" | "closed" }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="draft">Rascunho</SelectItem><SelectItem value="active">Ativa</SelectItem><SelectItem value="closed">Encerrada</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label>Descrição</Label><Textarea value={campaign.description} onChange={event => setCampaign(current => ({ ...current, description: event.target.value }))} placeholder="Objetivo, público e argumento principal." /></div><Button type="submit" disabled={createCampaign.isPending} className="w-full bg-[#1d2b2a] hover:bg-[#29413e]"><Plus className="mr-2 h-4 w-4" />{createCampaign.isPending ? "Criando..." : "Criar campanha"}</Button></form></CardContent></Card> : null}
    </div>

    <div className="grid gap-5 xl:grid-cols-2">
      <Card className="border-[#e8e1d4]"><CardContent className="p-6"><div className="flex items-center gap-3"><Target className="h-5 w-5 text-[#b18f4b]" /><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#b18f4b]">Meta de execução</p><h2 className="font-serif text-2xl text-[#1d2b2a]">Metas por vendedor</h2></div></div>{isAdmin ? <form onSubmit={submitGoal} className="mt-5 grid gap-3 sm:grid-cols-2"><Select value={goal.sellerId || undefined} onValueChange={value => setGoal(current => ({ ...current, sellerId: value }))}><SelectTrigger><SelectValue placeholder="Vendedor" /></SelectTrigger><SelectContent>{sellers.map(seller => <SelectItem key={seller.id} value={String(seller.id)}>{seller.name}</SelectItem>)}</SelectContent></Select><Input required type="month" value={goal.monthReference.slice(0, 7)} onChange={event => setGoal(current => ({ ...current, monthReference: `${event.target.value}-01` }))} /><Input required type="number" min="1" value={goal.targetAmount} onChange={event => setGoal(current => ({ ...current, targetAmount: event.target.value }))} placeholder="Meta R$" /><Button type="submit" disabled={createGoal.isPending} className="bg-[#1d2b2a] hover:bg-[#29413e]">Definir meta</Button></form> : null}<div className="mt-5 space-y-4">{goals.data?.length ? goals.data.map(item => <div key={item.goal.id}><div className="mb-2 flex justify-between gap-3 text-sm"><span className="font-medium text-[#1d2b2a]">{item.sellerName || "Vendedor"} · {new Date(item.goal.monthReference).toLocaleDateString("pt-BR", { month: "short", year: "numeric" })}</span><span className="text-muted-foreground">{money(item.currentAmount)} / {money(Number(item.goal.targetAmount))}</span></div><Progress value={Math.min(100, Number(item.goal.targetAmount) ? item.currentAmount / Number(item.goal.targetAmount) * 100 : 0)} className="h-2 bg-[#ece8dd] [&>div]:bg-[#b18f4b]" /></div>) : <p className="mt-6 text-sm text-muted-foreground">Ainda não há meta definida. É melhor definir uma antes de cobrar milagre de vendedor.</p>}</div></CardContent></Card>
      <Card className="border-[#e8e1d4]"><CardContent className="p-6"><div className="flex items-center gap-3"><CalendarRange className="h-5 w-5 text-[#b18f4b]" /><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#b18f4b]">Execução guiada</p><h2 className="font-serif text-2xl text-[#1d2b2a]">Playbooks do funil</h2></div></div>{isAdmin ? <form onSubmit={submitPlaybook} className="mt-5 space-y-3"><div className="grid grid-cols-[1fr_160px] gap-3"><Input required value={playbook.name} onChange={event => setPlaybook(current => ({ ...current, name: event.target.value }))} placeholder="Nome do playbook" /><Select value={playbook.stage} onValueChange={value => setPlaybook(current => ({ ...current, stage: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{stageOptions.map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><Textarea required value={playbook.guidance} onChange={event => setPlaybook(current => ({ ...current, guidance: event.target.value }))} placeholder="O que o vendedor deve fazer nesta etapa?" /><Textarea value={playbook.checklist} onChange={event => setPlaybook(current => ({ ...current, checklist: event.target.value }))} placeholder="Checklist opcional, um item por linha." /><Button type="submit" disabled={createPlaybook.isPending} variant="outline" className="w-full border-[#d9cfbd] text-[#1d2b2a]"><Plus className="mr-2 h-4 w-4" />{createPlaybook.isPending ? "Salvando..." : "Criar playbook"}</Button></form> : null}<div className="mt-5 space-y-3">{playbooks.data?.length ? playbooks.data.map(item => <div key={item.id} className="rounded-xl border border-[#ece6da] p-3"><div className="flex items-center justify-between gap-3"><p className="font-medium text-[#1d2b2a]">{item.name}</p><Badge variant="outline" className="border-[#e3d5bc] text-[#8a6b2d]">{stageOptions.find(([value]) => value === item.stage)?.[1]}</Badge></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-muted-foreground">{item.guidance}</p></div>) : <p className="mt-6 text-sm text-muted-foreground">Ainda não há playbook ativo. Crie o primeiro roteiro para parar de treinar equipe no grito.</p>}</div></CardContent></Card>
    </div>
  </div>;
}
