import { EmptyState, PageHeader, money } from "@/components/crm/ui";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { Award, BadgeDollarSign, CheckCircle2, Plus, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const statusText: Record<string, string> = { pending: "Aguardando", approved: "Aprovada", paid: "Paga", cancelled: "Cancelada" };
const statusTone: Record<string, string> = { pending: "bg-[#f4efe2] text-[#8a6b2d]", approved: "bg-[#e7f0e7] text-[#285043]", paid: "bg-[#dcefe9] text-[#1d5b53]", cancelled: "bg-[#f9e8df] text-[#a54920]" };

export default function Commissions() {
  const { user } = useAuth();
  const [campaignId, setCampaignId] = useState("all");
  const [campaignOpen, setCampaignOpen] = useState(false);
  const [commissionOpen, setCommissionOpen] = useState(false);
  const [campaign, setCampaign] = useState({ name: "", code: "", rate: "5", startsAt: "", endsAt: "" });
  const [commission, setCommission] = useState({ sellerId: "", campaignId: "none", baseAmount: "", rate: "5" });
  const overview = trpc.commissions.overview.useQuery(campaignId === "all" ? undefined : { campaignId: Number(campaignId) }, { refetchInterval: 30_000 });
  const utils = trpc.useUtils();
  const createCampaign = trpc.commissions.createCampaign.useMutation({ onSuccess: () => { toast.success("Campanha criada."); setCampaignOpen(false); utils.commissions.overview.invalidate(); }, onError: error => toast.error(error.message) });
  const record = trpc.commissions.record.useMutation({ onSuccess: ({ amount }) => { toast.success(`Comissão de ${money(amount)} lançada.`); setCommissionOpen(false); utils.commissions.overview.invalidate(); }, onError: error => toast.error(error.message) });
  const setStatus = trpc.commissions.setStatus.useMutation({ onSuccess: () => { toast.success("Status atualizado."); utils.commissions.overview.invalidate(); }, onError: error => toast.error(error.message) });
  const data = overview.data;
  const totals = useMemo(() => ({ sold: data?.ranking.reduce((sum, item) => sum + item.salesAmount, 0) ?? 0, commission: data?.ranking.reduce((sum, item) => sum + item.commissionAmount, 0) ?? 0, pending: data?.ranking.reduce((sum, item) => sum + item.pendingAmount, 0) ?? 0 }), [data]);
  const canManage = user?.role === "admin" || user?.role === "finance";
  if (user?.role === "service" || user?.role === "user") return <EmptyState title="Comissões restritas ao comercial e financeiro" body="Aqui tem venda, percentagem e dinheiro. Atendimento fica fora desta sala para a casa não virar bingo." />;

  const campaignDialog = <Dialog open={campaignOpen} onOpenChange={setCampaignOpen}><DialogTrigger asChild><Button variant="outline"><Plus className="mr-2 h-4 w-4" />Nova campanha</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle className="font-serif text-2xl">Nova campanha comercial</DialogTitle></DialogHeader><div className="grid gap-4"><div className="grid gap-2"><Label>Nome</Label><Input value={campaign.name} onChange={event => setCampaign({ ...campaign, name: event.target.value })} placeholder="Férias de Verão" /></div><div className="grid gap-2"><Label>Código</Label><Input value={campaign.code} onChange={event => setCampaign({ ...campaign, code: event.target.value })} placeholder="VERAO-2026" /></div><div className="grid gap-2"><Label>Comissão padrão (%)</Label><Input type="number" min="0" max="100" value={campaign.rate} onChange={event => setCampaign({ ...campaign, rate: event.target.value })} /></div><div className="grid grid-cols-2 gap-3"><div className="grid gap-2"><Label>Início</Label><Input type="date" value={campaign.startsAt} onChange={event => setCampaign({ ...campaign, startsAt: event.target.value })} /></div><div className="grid gap-2"><Label>Fim</Label><Input type="date" value={campaign.endsAt} onChange={event => setCampaign({ ...campaign, endsAt: event.target.value })} /></div></div><Button disabled={!campaign.name || !campaign.code || createCampaign.isPending} onClick={() => createCampaign.mutate({ name: campaign.name, code: campaign.code, commissionRate: Number(campaign.rate), startsAt: campaign.startsAt || undefined, endsAt: campaign.endsAt || undefined, status: "active" })} className="bg-[#1d2b2a] hover:bg-[#29413e]">Criar campanha</Button></div></DialogContent></Dialog>;
  const commissionDialog = <Dialog open={commissionOpen} onOpenChange={setCommissionOpen}><DialogTrigger asChild><Button className="bg-[#1d2b2a] hover:bg-[#29413e]"><WalletCards className="mr-2 h-4 w-4" />Lançar comissão</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle className="font-serif text-2xl">Lançar comissão</DialogTitle></DialogHeader><div className="grid gap-4"><div className="grid gap-2"><Label>Vendedor</Label><Select value={commission.sellerId} onValueChange={sellerId => setCommission({ ...commission, sellerId })}><SelectTrigger><SelectValue placeholder="Escolha o vendedor" /></SelectTrigger><SelectContent>{data?.sellers?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.name}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Campanha</Label><Select value={commission.campaignId} onValueChange={campaignId => setCommission({ ...commission, campaignId })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Sem campanha</SelectItem>{data?.campaigns?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.name}</SelectItem>)}</SelectContent></Select></div><div className="grid grid-cols-2 gap-3"><div className="grid gap-2"><Label>Base de cálculo</Label><Input type="number" min="0" value={commission.baseAmount} onChange={event => setCommission({ ...commission, baseAmount: event.target.value })} /></div><div className="grid gap-2"><Label>Percentual (%)</Label><Input type="number" min="0" max="100" value={commission.rate} onChange={event => setCommission({ ...commission, rate: event.target.value })} /></div></div><p className="rounded-xl bg-[#faf8f3] p-3 text-sm">Previsão: <b>{money(Number(commission.baseAmount || 0) * Number(commission.rate || 0) / 100)}</b></p><Button disabled={!commission.sellerId || !commission.baseAmount || record.isPending} onClick={() => record.mutate({ sellerId: Number(commission.sellerId), campaignId: commission.campaignId === "none" ? undefined : Number(commission.campaignId), baseAmount: Number(commission.baseAmount), rate: Number(commission.rate) })} className="bg-[#1d2b2a] hover:bg-[#29413e]">Lançar pendência</Button></div></DialogContent></Dialog>;

  return <div className="space-y-8"><PageHeader eyebrow="Comercial & repasse" title="Central de comissões" description="Acompanhe venda ganha, comissão prevista, pagamento e ranking por campanha sem fazer conta no guardanapo." action={<div className="flex gap-2">{user?.role === "admin" ? campaignDialog : null}{canManage ? commissionDialog : null}</div>} />
    <Card className="rounded-[1.35rem] border-[#e9e4da]"><CardContent className="flex flex-col gap-3 p-5 sm:flex-row sm:items-end sm:justify-between"><div><Label className="text-[10px] font-bold uppercase tracking-[.11em] text-[#8a6b2d]">Campanha</Label><Select value={campaignId} onValueChange={setCampaignId}><SelectTrigger className="mt-2 w-72"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Todas as campanhas</SelectItem>{data?.campaigns?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.code} · {item.name}</SelectItem>)}</SelectContent></Select></div><p className="text-xs text-muted-foreground">Venda ganha alimenta o ranking; comissão é lançada, aprovada e paga com trilha de status.</p></CardContent></Card>
    <section className="grid gap-4 md:grid-cols-3"><Card className="rounded-[1.35rem] bg-[#1d2b2a] text-white"><CardContent className="p-5"><BadgeDollarSign className="h-5 w-5 text-[#d6b774]" /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.13em] text-white/50">Venda ganha</p><p className="mt-1 font-serif text-3xl">{money(totals.sold)}</p></CardContent></Card><Card className="rounded-[1.35rem] border-[#e9e4da]"><CardContent className="p-5"><Award className="h-5 w-5 text-[#b18f4b]" /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.13em] text-[#8a6b2d]">Comissão lançada</p><p className="mt-1 font-serif text-3xl text-[#1d2b2a]">{money(totals.commission)}</p></CardContent></Card><Card className="rounded-[1.35rem] border-[#e9e4da]"><CardContent className="p-5"><WalletCards className="h-5 w-5 text-[#285043]" /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.13em] text-[#285043]">A pagar / aprovar</p><p className="mt-1 font-serif text-3xl text-[#1d2b2a]">{money(totals.pending)}</p></CardContent></Card></section>
    <section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card className="rounded-[1.35rem] border-[#e9e4da]"><CardHeader><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#b18f4b]">Placar da campanha</p><CardTitle className="mt-1 font-serif text-2xl text-[#1d2b2a]">Ranking de vendas</CardTitle></CardHeader><CardContent>{data?.ranking?.length ? <div className="space-y-3">{data.ranking.map(item => <div key={item.sellerId} className="grid grid-cols-[42px_1fr_auto] items-center gap-3 rounded-xl bg-[#faf8f3] p-4"><div className={`flex h-9 w-9 items-center justify-center rounded-full font-serif font-bold ${item.position === 1 ? "bg-[#c7a35a] text-[#1d2b2a]" : "bg-[#e8e3d9] text-[#52615c]"}`}>{item.position}</div><div><p className="font-semibold text-[#1d2b2a]">{item.sellerName}</p><p className="mt-1 text-xs text-muted-foreground">{item.wonCount} venda(s) ganha(s) · comissão {money(item.commissionAmount)}</p></div><p className="font-serif text-lg text-[#1d2b2a]">{money(item.salesAmount)}</p></div>)}</div> : <EmptyState title="Ainda não há ranking" body="Ganhe vendas, vincule campanha e o placar começa a expor quem está carregando o piano." />}</CardContent></Card><Card className="rounded-[1.35rem] border-[#e9e4da]"><CardHeader><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#b18f4b]">Campanhas</p><CardTitle className="mt-1 font-serif text-2xl text-[#1d2b2a]">Receita por frente</CardTitle></CardHeader><CardContent className="space-y-3">{data?.campaigns?.length ? data.campaigns.map(item => <div key={item.id} className="rounded-xl border border-[#ece7dd] p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-semibold text-[#1d2b2a]">{item.name}</p><p className="mt-1 text-xs text-muted-foreground">{item.code} · {Number(item.commissionRate)}% padrão</p></div><Badge className="bg-[#edf3ec] text-[#285043]">{item.status}</Badge></div><p className="mt-4 font-serif text-xl text-[#1d2b2a]">{money(item.salesAmount)}</p></div>) : <p className="rounded-xl bg-[#faf8f3] p-5 text-sm text-muted-foreground">Crie uma campanha para separar o jogo do comercial.</p>}</CardContent></Card></section>
    <Card className="rounded-[1.35rem] border-[#e9e4da]"><CardHeader><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#b18f4b]">Fila de repasse</p><CardTitle className="mt-1 font-serif text-2xl text-[#1d2b2a]">Comissões lançadas</CardTitle></CardHeader><CardContent>{data?.entries?.length ? <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="border-b text-[10px] font-bold uppercase tracking-[.1em] text-muted-foreground"><th className="px-3 py-3">Vendedor</th><th className="px-3 py-3">Campanha</th><th className="px-3 py-3">Base / %</th><th className="px-3 py-3">Comissão</th><th className="px-3 py-3">Status</th>{canManage ? <th className="px-3 py-3">Ação</th> : null}</tr></thead><tbody>{data.entries.map(({ commission: entry, sellerName, campaignName }) => <tr key={entry.id} className="border-b border-[#f1ede5]"><td className="px-3 py-4 font-medium text-[#1d2b2a]">{sellerName || "Vendedor"}</td><td className="px-3 py-4 text-muted-foreground">{campaignName || "Avulsa"}</td><td className="px-3 py-4">{money(entry.baseAmount)} · {Number(entry.rate)}%</td><td className="px-3 py-4 font-semibold">{money(entry.amount)}</td><td className="px-3 py-4"><Badge className={`border-0 ${statusTone[entry.status]}`}>{statusText[entry.status]}</Badge></td>{canManage ? <td className="px-3 py-4">{entry.status === "pending" ? <Button size="sm" variant="outline" onClick={() => setStatus.mutate({ id: entry.id, status: "approved" })}>Aprovar</Button> : entry.status === "approved" ? <Button size="sm" className="bg-[#1d2b2a]" onClick={() => setStatus.mutate({ id: entry.id, status: "paid" })}>Marcar paga</Button> : <CheckCircle2 className="h-4 w-4 text-[#285043]" />}</td> : null}</tr>)}</tbody></table></div> : <EmptyState title="Nenhuma comissão lançada" body="Quando venda e regra de comissão se encontrarem, o repasse aparece aqui sem fofoca de corredor." />}</CardContent></Card>
  </div>;
}
