import { EmptyState, PageHeader, money } from "@/components/crm/ui";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { Award, BadgeDollarSign, Trophy, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";

export default function Commissions() {
  const [campaignId, setCampaignId] = useState("all");
  const overview = trpc.commissions.overview.useQuery(campaignId === "all" ? undefined : { campaignId: Number(campaignId) }, { refetchInterval: 30_000 });
  const data = overview.data;
  const totals = useMemo(() => ({ sold: data?.ranking.reduce((sum, item) => sum + item.salesAmount, 0) ?? 0, commission: data?.ranking.reduce((sum, item) => sum + item.commissionAmount, 0) ?? 0, pending: data?.ranking.reduce((sum, item) => sum + item.pendingAmount, 0) ?? 0 }), [data]);
  return <div className="space-y-8"><PageHeader eyebrow="Comercial & repasse" title="Central de comissões" description="Ranking, comissão e termômetro de meta no mesmo painel — agora ninguém finge que não viu o placar." action={<Button className="bg-[#1d2b2a] hover:bg-[#29413e]"><WalletCards className="mr-2 h-4 w-4" />Lançar comissão</Button>} />
    <Card className="rounded-[1.35rem] border-[#e9e4da]"><CardContent className="flex flex-col gap-3 p-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#8a6b2d]">Campanha</p><Select value={campaignId} onValueChange={setCampaignId}><SelectTrigger className="mt-2 w-72"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Todas as campanhas</SelectItem>{data?.campaigns?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.code} · {item.name}</SelectItem>)}</SelectContent></Select></div><p className="text-xs text-muted-foreground">Filtro aplicado ao ranking e aos repasses.</p></CardContent></Card>
    <section className="grid gap-4 md:grid-cols-3"><Card className="rounded-[1.35rem] bg-[#1d2b2a] text-white"><CardContent className="p-5"><BadgeDollarSign className="h-5 w-5 text-[#d6b774]" /><p className="mt-5 text-[10px] font-bold uppercase text-white/50">Venda ganha</p><p className="mt-1 font-serif text-3xl">{money(totals.sold)}</p></CardContent></Card><Card className="rounded-[1.35rem]"><CardContent className="p-5"><Award className="h-5 w-5 text-[#b18f4b]" /><p className="mt-5 text-[10px] font-bold uppercase text-[#8a6b2d]">Comissão lançada</p><p className="mt-1 font-serif text-3xl">{money(totals.commission)}</p></CardContent></Card><Card className="rounded-[1.35rem]"><CardContent className="p-5"><WalletCards className="h-5 w-5 text-[#285043]" /><p className="mt-5 text-[10px] font-bold uppercase text-[#285043]">A pagar / aprovar</p><p className="mt-1 font-serif text-3xl">{money(totals.pending)}</p></CardContent></Card></section>
    <section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card className="rounded-[1.35rem]"><CardHeader><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#b18f4b]">Meta mensal</p><CardTitle className="font-serif text-2xl">Termômetro de vendas</CardTitle></CardHeader><CardContent className="space-y-4">{data?.goals?.length ? data.goals.map(goal => { const seller = data.sellers?.find(item => item.id === goal.sellerId)?.name || "Vendedor"; return <div key={goal.sellerId} className="rounded-xl bg-[#faf8f3] p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold text-[#1d2b2a]">{seller}</p><p className="mt-1 text-xs text-muted-foreground">{money(goal.currentAmount)} de {money(goal.targetAmount)}</p></div><span className="font-serif text-lg text-[#1d2b2a]">{goal.progress.toFixed(0)}%</span></div><Progress value={goal.progress} className="mt-3 h-2 bg-[#e5e0d5] [&>div]:bg-[#b99348]" /></div>; }) : <EmptyState title="Nenhuma meta definida" body="Defina meta na Central de Vendas e o termômetro para de marcar febre de cadeira." />}</CardContent></Card><Card className="rounded-[1.35rem]"><CardHeader><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#b18f4b]">Placar</p><CardTitle className="font-serif text-2xl">Ranking de vendas</CardTitle></CardHeader><CardContent className="space-y-3">{data?.ranking?.length ? data.ranking.map(item => <div key={item.sellerId} className="flex items-center gap-3 rounded-xl bg-[#faf8f3] p-4"><Trophy className="h-5 w-5 text-[#b99348]" /><div className="min-w-0 flex-1"><p className="font-semibold text-[#1d2b2a]">{item.position}º · {item.sellerName}</p><p className="mt-1 text-xs text-muted-foreground">{item.wonCount} venda(s) · comissão {money(item.commissionAmount)}</p></div><p className="font-serif">{money(item.salesAmount)}</p></div>) : <EmptyState title="Ainda não há ranking" body="Ganhe venda e a hierarquia aparece sem piedade." />}</CardContent></Card></section></div>;
}
