import { EmptyState, PageHeader, money } from "@/components/crm/ui";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { Award, BadgeDollarSign, CalendarRange, ShieldCheck, SlidersHorizontal, Trophy, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";

const roleLabel: Record<string, string> = { promoter: "Captador", qualifier: "Qualificador", liner: "Liner", closer: "Fechador", ftb: "FTB · front-back", room_manager: "Gerente de sala", finance: "Financeiro" };
const coverageLabel: Record<string, string> = { insufficient: "Amostra insuficiente", maturing: "Em maturação", mature: "Base madura" };

export default function Commissions() {
  const [campaignId, setCampaignId] = useState("all");
  const [closingMonth, setClosingMonth] = useState(() => new Date().toISOString().slice(0, 7));
  const [filtersOpen, setFiltersOpen] = useState(false);
  const overview = trpc.commissions.overview.useQuery({ ...(campaignId === "all" ? {} : { campaignId: Number(campaignId) }), closingMonth }, { refetchInterval: 30_000 });
  const scorecardsQuery = trpc.commissions.scorecards.useQuery({ minimumMaturedSales: 10 }, { refetchInterval: 30_000 });
  const portfolioScorecardsQuery = trpc.finance.portfolioScorecards.useQuery(undefined, { refetchInterval: 30_000 });
  const data = overview.data;
  const scorecards = scorecardsQuery.data?.scorecards ?? [];
  const rankedScorecards = useMemo(() => scorecards.map(card => ({ ...card, position: scorecards.filter(peer => peer.role === card.role).sort((left, right) => right.cashConfirmed - left.cashConfirmed || right.vgvFormalized - left.vgvFormalized || left.userName.localeCompare(right.userName)).findIndex(peer => peer.userId === card.userId) + 1 })), [scorecards]);
  const totals = useMemo(() => ({ sold: data?.ranking.reduce((sum, item) => sum + item.salesAmount, 0) ?? 0, commission: data?.ranking.reduce((sum, item) => sum + item.commissionAmount, 0) ?? 0, pending: data?.ranking.reduce((sum, item) => sum + item.pendingAmount, 0) ?? 0 }), [data]);
  const bordero = data?.bordero;
  const campaignName = campaignId === "all" ? "Todas as campanhas" : data?.campaigns?.find(item => item.id === Number(campaignId))?.name ?? "Campanha selecionada";
  const filterFields = <div className="grid gap-3 sm:grid-cols-2"><div><p className="tgr-data-label text-[#8a6b2d]">Campanha</p><Select value={campaignId} onValueChange={setCampaignId}><SelectTrigger className="mt-2 w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Todas as campanhas</SelectItem>{data?.campaigns?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.code} · {item.name}</SelectItem>)}</SelectContent></Select></div><div><p className="tgr-data-label text-[#8a6b2d]">Fechamento do borderô</p><input type="month" value={closingMonth} onChange={event => setClosingMonth(event.target.value)} className="mt-2 h-9 w-full rounded-md border border-input bg-background px-3 text-sm" /></div></div>;

  return <div className="space-y-8">
    <PageHeader eyebrow="Comercial & repasse" title="Central de comissões" description="Ranking, comissão e termômetro de meta no mesmo painel — agora ninguém finge que não viu o placar." action={<Button className="bg-[#1d2b2a] hover:bg-[#29413e]"><WalletCards className="mr-2 h-4 w-4" />Lançar comissão</Button>} />
    <Card className="rounded-xl border-[#e9e4da] shadow-none"><CardContent className="p-5"><div className="hidden items-end justify-between gap-4 sm:flex"><div className="w-full max-w-xl">{filterFields}</div><p className="text-xs text-muted-foreground">Ranking e repasses no ciclo selecionado.</p></div><div className="sm:hidden"><p className="tgr-data-label text-[#94702e]">Recorte do borderô</p><p className="mt-1 font-serif text-lg text-[#1d2b2a]">{closingMonth}</p><p className="mt-1 text-xs text-muted-foreground">{campaignName}</p><Button variant="outline" className="mt-4 w-full justify-start" onClick={() => setFiltersOpen(true)}><SlidersHorizontal className="mr-2 h-4 w-4" />Ajustar campanha e ciclo</Button></div></CardContent></Card>
    <section className="grid gap-4 md:grid-cols-4"><Card className="rounded-xl bg-[#1d2b2a] text-white shadow-none"><CardContent className="p-5"><BadgeDollarSign className="h-5 w-5 text-[#d6b774]" /><p className="mt-5 text-[10px] font-bold uppercase text-white/50">Venda ganha</p><p className="mt-1 font-serif text-3xl tabular-nums">{money(totals.sold)}</p></CardContent></Card><Card className="rounded-xl shadow-none"><CardContent className="p-5"><Award className="h-5 w-5 text-[#b18f4b]" /><p className="mt-5 text-[10px] font-bold uppercase text-[#8a6b2d]">Comissão lançada</p><p className="mt-1 font-serif text-3xl tabular-nums">{money(totals.commission)}</p></CardContent></Card><Card className="rounded-xl shadow-none"><CardContent className="p-5"><WalletCards className="h-5 w-5 text-[#285043]" /><p className="mt-5 text-[10px] font-bold uppercase text-[#285043]">Borderô recebido</p><p className="mt-1 font-serif text-3xl tabular-nums">{money(bordero?.paid ?? 0)}</p><p className="mt-2 text-xs text-muted-foreground">{money(bordero?.locked ?? 0)} travado na janela</p></CardContent></Card><Card className="rounded-xl shadow-none"><CardContent className="p-5"><WalletCards className="h-5 w-5 text-[#285043]" /><p className="mt-5 text-[10px] font-bold uppercase text-[#285043]">A receber / aprovar</p><p className="mt-1 font-serif text-3xl tabular-nums">{money((bordero?.payable ?? 0) + (bordero?.overdue ?? 0))}</p><p className="mt-2 text-xs text-muted-foreground">{money(bordero?.cancelled ?? 0)} cancelado</p></CardContent></Card></section>
    <section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card className="rounded-[1.35rem]"><CardHeader><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#b18f4b]">Meta mensal</p><CardTitle className="font-serif text-2xl">Termômetro de vendas</CardTitle></CardHeader><CardContent className="space-y-4">{data?.goals?.length ? data.goals.map(goal => { const seller = data.sellers?.find(item => item.id === goal.sellerId)?.name || "Vendedor"; return <div key={goal.sellerId} className="rounded-xl bg-[#faf8f3] p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold text-[#1d2b2a]">{seller}</p><p className="mt-1 text-xs text-muted-foreground">{money(goal.currentAmount)} de {money(goal.targetAmount)}</p></div><span className="font-serif text-lg text-[#1d2b2a]">{goal.progress.toFixed(0)}%</span></div><Progress value={goal.progress} className="mt-3 h-2 bg-[#e5e0d5] [&>div]:bg-[#b99348]" /></div>; }) : <EmptyState title="Nenhuma meta definida" body="Defina meta na Central de Vendas e o termômetro para de marcar febre de cadeira." />}</CardContent></Card><Card className="rounded-[1.35rem]"><CardHeader><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#b18f4b]">Placar</p><CardTitle className="font-serif text-2xl">Ranking de vendas</CardTitle></CardHeader><CardContent className="space-y-3">{data?.ranking?.length ? data.ranking.map(item => <div key={item.sellerId} className="flex items-center gap-3 rounded-xl bg-[#faf8f3] p-4"><Trophy className="h-5 w-5 text-[#b99348]" /><div className="min-w-0 flex-1"><p className="font-semibold text-[#1d2b2a]">{item.position}º · {item.sellerName}</p><p className="mt-1 text-xs text-muted-foreground">{item.wonCount} venda(s) · comissão {money(item.commissionAmount)}</p></div><p className="font-serif">{money(item.salesAmount)}</p></div>) : <EmptyState title="Ainda não há ranking" body="Ganhe venda e a hierarquia aparece sem piedade." />}</CardContent></Card></section>
    <Card className="rounded-xl border-[#dcd4c4] shadow-none"><CardHeader><div className="flex items-start gap-3"><div className="rounded-lg bg-[#efe4c5] p-2"><ShieldCheck className="h-5 w-5 text-[#71531a]" /></div><div><p className="tgr-data-label text-[#8a6b2d]">Qualidade de receita</p><CardTitle className="mt-1 font-serif text-2xl">Scorecard por papel comercial</CardTitle><p className="mt-1 text-sm text-muted-foreground">Produção só vira ranking de verdade quando a venda amadurece. Cada profissional disputa apenas dentro do próprio papel; FTB não é contado duas vezes e amostra pequena não ganha coroa de plástico.</p></div></div></CardHeader><CardContent>{scorecardsQuery.data?.truncated ? <div className="mb-4 rounded-xl border border-[#ead8ad] bg-[#fff9e9] p-3 text-xs text-[#71531a]"><p className="font-semibold">Atenção: scorecard baseado em amostra limitada.</p><p className="mt-1">Fontes no limite: {scorecardsQuery.data.truncatedSources.join(", ")}. Revalide o placar antes de usar para cobrança ou comissão.</p></div> : null}{scorecardsQuery.isLoading ? <p className="text-sm text-muted-foreground">Lendo maturação da carteira…</p> : rankedScorecards.length ? <div className="grid gap-3 lg:grid-cols-2">{rankedScorecards.map(card => <div key={`${card.userId}-${card.role}`} className="border-b border-[#ece6da] py-4 first:pt-0 last:border-b-0 lg:border lg:bg-[#faf8f3] lg:p-4"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-[#1d2b2a]">{card.position}º · {roleLabel[card.role] ?? card.role} · {card.userName}</p><p className="mt-1 text-xs text-muted-foreground">{coverageLabel[card.coverage] ?? card.coverage} · {card.maturedSales} venda(s) na janela de maturação</p></div><span className="shrink-0 rounded-md bg-white px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-[#71531a]">{card.cancellationRate === null ? "Sem coorte" : `${card.cancellationRate}% distrato`}</span></div><div className="mt-4 grid grid-cols-3 gap-3 text-xs"><div><p className="text-muted-foreground">VGV atribuído</p><p className="mt-1 font-semibold tabular-nums text-[#1d2b2a]">{money(card.vgvFormalized)}</p></div><div><p className="text-muted-foreground">Caixa confirmado</p><p className="mt-1 font-semibold tabular-nums text-[#1d2b2a]">{money(card.cashConfirmed)}</p></div><div><p className="text-muted-foreground">Vendas atribuídas</p><p className="mt-1 font-semibold tabular-nums text-[#1d2b2a]">{card.attributedSales}</p></div></div></div>)}</div> : <EmptyState title="Sem scorecard ainda" body="Quando contratos, captações e entradas caminharem juntos, a qualidade aparece aqui — sem dar medalha para venda fantasma." />}</CardContent></Card>
    <Card className="rounded-xl border-[#dcd4c4] shadow-none"><CardHeader><p className="tgr-data-label text-[#8a6b2d]">Carteira financeira</p><CardTitle className="mt-1 font-serif text-2xl">Recuperação por responsável</CardTitle><p className="mt-1 text-sm text-muted-foreground">Só conta recebimento ocorrido depois da atribuição da carteira. Quem baixou parcela não rouba mérito de quem recuperou.</p></CardHeader><CardContent>{portfolioScorecardsQuery.isLoading ? <p className="text-sm text-muted-foreground">Lendo carteiras ativas…</p> : portfolioScorecardsQuery.data?.length ? <div className="grid gap-3 lg:grid-cols-2">{portfolioScorecardsQuery.data.map((card, index) => <div key={card.ownerUserId} className="border-b border-[#ece6da] py-4 first:pt-0 last:border-b-0 lg:border lg:bg-[#faf8f3] lg:p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-[#1d2b2a]">{index + 1}º · Financeiro · {card.ownerName}</p><p className="mt-1 text-xs text-muted-foreground">{card.assignedContracts} contrato(s) ativo(s) na carteira</p></div><span className="shrink-0 rounded-md bg-white px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-[#71531a]">{card.regularizationRate === null ? "Sem base" : `${card.regularizationRate}% regularizado`}</span></div><div className="mt-4 grid grid-cols-3 gap-3 text-xs"><div><p className="text-muted-foreground">Recuperado</p><p className="mt-1 font-semibold tabular-nums text-[#1d2b2a]">{money(card.recoveredAfterAssignment)}</p></div><div><p className="text-muted-foreground">Em aberto</p><p className="mt-1 font-semibold tabular-nums text-[#1d2b2a]">{money(card.openAmount)}</p></div><div><p className="text-muted-foreground">Em atraso</p><p className="mt-1 font-semibold tabular-nums text-[#a23a32]">{money(card.overdueAmount)}</p></div></div></div>)}</div> : <EmptyState title="Sem carteira atribuída" body="Atribua um responsável financeiro na ficha do contrato para acompanhar recuperação, aberto e atraso sem gambiarra." />}</CardContent></Card>
    <Dialog open={filtersOpen} onOpenChange={setFiltersOpen}><DialogContent className="sm:hidden"><DialogHeader><DialogTitle className="font-serif text-2xl text-[#1d2b2a]">Recorte de comissões</DialogTitle><DialogDescription>Campanha e ciclo determinam ranking, borderô e carteira exibidos abaixo.</DialogDescription></DialogHeader>{filterFields}<Button className="mt-2 bg-[#1d2b2a] hover:bg-[#29413e]" onClick={() => setFiltersOpen(false)}><CalendarRange className="mr-2 h-4 w-4" />Aplicar recorte</Button></DialogContent></Dialog>
  </div>;
}
