import { EmptyState, PageHeader, money, StatusPill, dateLabel } from "@/components/crm/ui";
import { RevenueQualityCard } from "@/components/crm/RevenueQualityCard";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, FileUp, Paperclip, RefreshCw, ShieldCheck } from "lucide-react";
import { ChangeEvent, FormEvent, useState } from "react";
import { Link, useRoute } from "wouter";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";

type ContractStatus = "draft" | "pending_signature" | "active" | "overdue" | "cancelled" | "closed";

export default function ContractDetail() {
  const [, params] = useRoute("/contratos/:id");
  const id = Number(params?.id ?? 0);
  const [uploadOpen, setUploadOpen] = useState(false);
  const [cancellationOpen, setCancellationOpen] = useState(false);
  const [status, setStatus] = useState<ContractStatus>("draft");
  const [file, setFile] = useState<File | null>(null);
  const [category, setCategory] = useState("Contrato");
  const [cancellationReason, setCancellationReason] = useState("");
  const [portfolioOwnerId, setPortfolioOwnerId] = useState("");
  const [portfolioNotes, setPortfolioNotes] = useState("");
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const detail = trpc.contracts.detail.useQuery({ id }, { enabled: Boolean(id) });
  const cancellationSimulation = trpc.contracts.simulateCancellation.useQuery({ contractId: id }, { enabled: Boolean(id) });
  const updateStatus = trpc.contracts.updateStatus.useMutation({ onSuccess: () => { utils.contracts.detail.invalidate({ id }); utils.contracts.list.invalidate(); toast.success("Status do contrato atualizado."); }, onError: error => toast.error(error.message) });
  const upload = trpc.contracts.uploadDocument.useMutation({ onSuccess: () => { utils.contracts.detail.invalidate({ id }); setUploadOpen(false); setFile(null); toast.success("Documento contratual anexado para conferência."); }, onError: error => toast.error(error.message) });
  const signDocument = trpc.contracts.markDocumentSigned.useMutation({ onSuccess: () => { utils.contracts.detail.invalidate({ id }); toast.success("Assinatura confirmada com trilha de auditoria."); }, onError: error => toast.error(error.message) });
  const requestCancellation = trpc.contracts.requestCancellation.useMutation({ onSuccess: () => { utils.contracts.detail.invalidate({ id }); setCancellationOpen(false); setCancellationReason(""); toast.success("Distrato enviado para aprovação humana."); }, onError: error => toast.error(error.message) });
  const decideCancellation = trpc.contracts.decideCancellation.useMutation({ onSuccess: () => { utils.contracts.detail.invalidate({ id }); toast.success("Decisão de distrato registrada."); }, onError: error => toast.error(error.message) });
  const executeCancellation = trpc.contracts.executeCancellation.useMutation({ onSuccess: () => { utils.contracts.detail.invalidate({ id }); utils.contracts.list.invalidate(); toast.success("Distrato aprovado executado com trilha auditável."); }, onError: error => toast.error(error.message) });
  const portfolioAssignments = trpc.finance.portfolioAssignments.useQuery({ contractId: id }, { enabled: Boolean(id) });
  const portfolioCandidates = trpc.finance.portfolioCandidates.useQuery();
  const assignPortfolioOwner = trpc.finance.assignPortfolioOwner.useMutation({ onSuccess: () => { utils.finance.portfolioAssignments.invalidate({ contractId: id }); setPortfolioOwnerId(""); setPortfolioNotes(""); toast.success("Carteira financeira atribuída com trilha de responsabilidade."); }, onError: error => toast.error(error.message) });

  const submitDocument = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!file) return toast.error("Escolha um arquivo.");
    const base64 = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
    upload.mutate({ contractId: id, category, filename: file.name, contentType: file.type || "application/octet-stream", base64, signed: false });
  };

  if (detail.isLoading) return <p className="text-sm text-muted-foreground">Abrindo pasta contratual...</p>;
  if (!detail.data) return <EmptyState title="Contrato não encontrado" body="Esta pasta não existe mais ou o endereço foi digitado errado." action={<Button asChild className="bg-[#1d2b2a]"><Link href="/contratos">Voltar para contratos</Link></Button>} />;

  const { contract, customerName, customerEmail, customerPhone, installments, documents, cancellationRequests } = detail.data;
  const currentStatus = status === "draft" && contract.status !== "draft" ? contract.status : status;
  const latestCancellation = cancellationRequests[0];

  return <div className="space-y-6">
    <Link href="/contratos" className="inline-flex items-center gap-2 text-xs font-semibold text-[#8a6b2d]"><ArrowLeft className="h-3.5 w-3.5" />Voltar para contratos</Link>
    <PageHeader eyebrow="Pasta contratual" title={contract.number} description={`${customerName} · ${contract.usageModel.replaceAll("_", " ")} · ${money(contract.totalAmount)}`} action={<div className="flex flex-wrap gap-2">
      <Dialog open={uploadOpen} onOpenChange={setUploadOpen}><DialogTrigger asChild><Button variant="outline" className="border-[#d9cfbd]"><Paperclip className="mr-2 h-4 w-4" />Anexar documento</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle className="font-serif text-2xl">Anexo contratual</DialogTitle></DialogHeader><form className="grid gap-4 py-2" onSubmit={submitDocument}><div className="grid gap-2"><Label>Categoria</Label><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Contrato">Contrato</SelectItem><SelectItem value="Contrato assinado">Contrato assinado</SelectItem><SelectItem value="Aditivo">Aditivo</SelectItem><SelectItem value="Comprovante">Comprovante</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label>Arquivo (máx. 5 MB)</Label><Input type="file" accept="application/pdf,image/*,.doc,.docx" onChange={(event: ChangeEvent<HTMLInputElement>) => setFile(event.target.files?.[0] ?? null)} /></div><Button disabled={upload.isPending} className="bg-[#1d2b2a] hover:bg-[#29413e]"><FileUp className="mr-2 h-4 w-4" />{upload.isPending ? "Enviando..." : "Guardar documento"}</Button></form></DialogContent></Dialog>
      <Select value={currentStatus} onValueChange={value => { const next = value as ContractStatus; setStatus(next); updateStatus.mutate({ id, status: next }); }}><SelectTrigger className="w-[190px] bg-[#1d2b2a] text-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="draft">Rascunho</SelectItem><SelectItem value="pending_signature">Aguardando assinatura</SelectItem><SelectItem value="active">Ativo</SelectItem><SelectItem value="overdue">Inadimplente</SelectItem><SelectItem value="closed">Encerrado</SelectItem></SelectContent></Select>
    </div>} />
    {detail.data.truncated ? <p className="rounded-xl border border-[#ead8ad] bg-[#fff9e9] p-3 text-xs text-[#71531a]">Atenção: {detail.data.truncatedSources.join(", ")} excedem o limite operacional. Exibindo apenas o recorte carregado da pasta contratual.</p> : null}
    <div className="grid gap-5 xl:grid-cols-[1.1fr_1.9fr]">
      <div className="space-y-5">
        <Card className="rounded-xl border-[#e9e4da] shadow-none"><CardHeader className="border-b border-[#eee9df] pb-4"><p className="tgr-data-label text-[#94702e]">Contrato e associado</p><CardTitle className="mt-1 font-serif text-xl text-[#1d2b2a]">Resumo</CardTitle></CardHeader><CardContent className="space-y-3 pt-5 text-sm"><div className="flex items-center justify-between"><span className="text-muted-foreground">Status</span><StatusPill value={contract.status} /></div><div className="flex justify-between gap-4"><span className="text-muted-foreground">Associado</span><span className="text-right font-medium">{customerName}</span></div><div className="flex justify-between gap-4"><span className="text-muted-foreground">E-mail</span><span className="text-right">{customerEmail || "—"}</span></div><div className="flex justify-between gap-4"><span className="text-muted-foreground">Telefone</span><span>{customerPhone || "—"}</span></div><div className="border-t border-[#eee9df] pt-3"><p className="tgr-data-label">Valor contratado</p><p className="mt-1 font-serif text-3xl tabular-nums text-[#1d2b2a]">{money(contract.totalAmount)}</p></div></CardContent></Card>
        <RevenueQualityCard contractId={id} />
        <PortfolioOwnerCard assignments={portfolioAssignments.data ?? []} candidates={portfolioCandidates.data ?? []} selectedOwnerId={portfolioOwnerId} notes={portfolioNotes} pending={assignPortfolioOwner.isPending} onOwnerChange={setPortfolioOwnerId} onNotesChange={setPortfolioNotes} onAssign={() => assignPortfolioOwner.mutate({ contractId: id, ownerUserId: Number(portfolioOwnerId), notes: portfolioNotes || null })} />
        <CancellationCard simulation={cancellationSimulation.data} request={latestCancellation} open={cancellationOpen} setOpen={setCancellationOpen} reason={cancellationReason} setReason={setCancellationReason} isCancelled={contract.status === "cancelled"} requestPending={requestCancellation.isPending} decisionPending={decideCancellation.isPending} executionPending={executeCancellation.isPending} onRequest={() => requestCancellation.mutate({ contractId: id, reason: cancellationReason })} onDecision={(decision) => decideCancellation.mutate({ requestId: latestCancellation.id, decision })} onExecute={() => executeCancellation.mutate({ requestId: latestCancellation.id })} />
        <DocumentsCard documents={documents} canSign={user?.role === "admin"} signPending={signDocument.isPending} onSign={documentId => signDocument.mutate({ documentId })} />
      </div>
      <Card className="overflow-hidden rounded-xl border-[#e9e4da] shadow-none"><CardHeader className="border-b border-[#eee9df]"><div className="flex items-center justify-between"><div><p className="tgr-data-label text-[#94702e]">Cronograma financeiro</p><CardTitle className="mt-1 font-serif text-2xl text-[#1d2b2a]">Parcelas</CardTitle></div><RefreshCw className="h-5 w-5 text-[#b18f4b]" /></div></CardHeader><CardContent className="p-0">{installments.map(item => <div key={item.id} className="grid grid-cols-[56px_1fr_1fr_auto] items-center gap-3 border-t border-[#f0ece4] px-5 py-4 text-sm first:border-t-0 sm:grid-cols-[80px_1fr_1fr_auto] sm:px-6"><span className="font-semibold text-[#1d2b2a]">#{item.sequence}</span><span>{dateLabel(item.dueDate)}</span><strong className="tabular-nums">{money(item.amount)}</strong><StatusPill value={item.status} /></div>)}</CardContent></Card>
    </div>
  </div>;
}

function CancellationCard({ simulation, request, open, setOpen, reason, setReason, isCancelled, requestPending, decisionPending, executionPending, onRequest, onDecision, onExecute }: { simulation?: { penalty: number; refund: number }; request?: { id: number; status: string; reason: string }; open: boolean; setOpen: (value: boolean) => void; reason: string; setReason: (value: string) => void; isCancelled: boolean; requestPending: boolean; decisionPending: boolean; executionPending: boolean; onRequest: () => void; onDecision: (value: "approved" | "rejected") => void; onExecute: () => void }) {
  return <Card className="rounded-xl border-[#e9e4da] shadow-none"><CardHeader className="border-b border-[#eee9df] pb-4"><p className="tgr-data-label text-[#94702e]">Governança contratual</p><CardTitle className="mt-1 font-serif text-xl text-[#1d2b2a]">Distrato auditável</CardTitle></CardHeader><CardContent className="space-y-3 pt-5 text-sm"><p className="text-muted-foreground">{simulation ? `Simulação: multa ${money(simulation.penalty)} · devolução ${money(simulation.refund)}.` : "Calculando impacto conforme a política do empreendimento..."}</p>{request ? <div className="rounded-lg bg-[#faf8f3] p-3"><p className="font-medium text-[#1d2b2a]">Solicitação #{request.id} · {request.status}</p><p className="mt-1 text-xs text-muted-foreground">{request.reason}</p>{request.status === "requested" && <div className="mt-3 grid grid-cols-2 gap-2"><Button variant="outline" disabled={decisionPending} onClick={() => onDecision("rejected")}>Rejeitar</Button><Button className="bg-[#1d2b2a] hover:bg-[#29413e]" disabled={decisionPending} onClick={() => onDecision("approved")}>Aprovar</Button></div>}{request.status === "approved" && <Button className="mt-3 w-full bg-[#9b3f32] hover:bg-[#7c3026]" disabled={executionPending} onClick={onExecute}>{executionPending ? "Executando..." : "Executar distrato aprovado"}</Button>}</div> : <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" className="w-full border-[#b18f4b] text-[#8a6b2d]" disabled={isCancelled}>Solicitar revisão de distrato</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle className="font-serif text-2xl">Solicitar distrato</DialogTitle></DialogHeader><div className="grid gap-4 py-2"><p className="text-sm text-muted-foreground">A solicitação congela esta simulação e exige aprovação humana antes de qualquer cancelamento.</p><textarea value={reason} onChange={event => setReason(event.target.value)} className="min-h-28 rounded-md border border-input bg-transparent p-3 text-sm" placeholder="Motivo documentado do distrato" /><Button disabled={reason.trim().length < 3 || requestPending} className="bg-[#1d2b2a] hover:bg-[#29413e]" onClick={onRequest}>{requestPending ? "Enviando..." : "Enviar para aprovação"}</Button></div></DialogContent></Dialog>}</CardContent></Card>;
}

function PortfolioOwnerCard({ assignments, candidates, selectedOwnerId, notes, pending, onOwnerChange, onNotesChange, onAssign }: { assignments: Array<{ assignment: { id: number; startsAt: Date; notes: string | null }; ownerName: string | null; ownerEmail: string | null }>; candidates: Array<{ id: number; name: string | null; email: string | null }>; selectedOwnerId: string; notes: string; pending: boolean; onOwnerChange: (value: string) => void; onNotesChange: (value: string) => void; onAssign: () => void }) {
  const current = assignments[0];
  return <Card className="rounded-[1.35rem] border-[#e9e4da]"><CardHeader><CardTitle className="font-serif text-xl text-[#1d2b2a]">Responsável financeiro</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><div className="rounded-xl bg-[#faf8f3] p-3"><p className="font-medium text-[#1d2b2a]">{current?.ownerName || current?.ownerEmail || "Sem carteira atribuída"}</p><p className="mt-1 text-xs text-muted-foreground">{current ? `Desde ${new Date(current.assignment.startsAt).toLocaleDateString("pt-BR")}${current.assignment.notes ? ` · ${current.assignment.notes}` : ""}` : "Quem cria ou baixa lançamento não vira automaticamente dono da cobrança."}</p></div><div className="grid gap-2"><Label>Transferir / atribuir carteira</Label><Select value={selectedOwnerId || undefined} onValueChange={onOwnerChange}><SelectTrigger><SelectValue placeholder="Escolher responsável" /></SelectTrigger><SelectContent>{candidates.map(candidate => <SelectItem key={candidate.id} value={String(candidate.id)}>{candidate.name || candidate.email || `Usuário #${candidate.id}`}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Motivo da atribuição</Label><Input value={notes} onChange={event => onNotesChange(event.target.value)} placeholder="Ex.: carteira de inadimplência da sala A" /></div><Button className="w-full bg-[#1d2b2a] hover:bg-[#29413e]" disabled={!selectedOwnerId || pending} onClick={onAssign}>{pending ? "Atribuindo..." : "Salvar responsável financeiro"}</Button></CardContent></Card>;
}

function DocumentsCard({ documents, canSign, signPending, onSign }: { documents: Array<{ id: number; storageKey: string; filename: string; category: string; signed: boolean }>; canSign: boolean; signPending: boolean; onSign: (documentId: number) => void }) {
  return <Card className="rounded-[1.35rem] border-[#e9e4da]"><CardHeader><CardTitle className="font-serif text-xl text-[#1d2b2a]">Documentos</CardTitle></CardHeader><CardContent className="space-y-2">{documents.length ? documents.map(document => <div key={document.id} className="flex items-center gap-2 rounded-xl bg-[#faf8f3] p-3 text-sm"><a href={`/manus-storage/${document.storageKey}`} target="_blank" rel="noreferrer" className="flex min-w-0 flex-1 items-center justify-between rounded-lg hover:bg-[#f3efe6]"><div className="min-w-0"><p className="truncate font-medium text-[#1d2b2a]">{document.filename}</p><p className="mt-1 text-[11px] text-muted-foreground">{document.category} · {document.signed ? "assinado e confirmado" : "aguardando confirmação"}</p></div><Paperclip className="ml-2 h-4 w-4 shrink-0 text-[#b18f4b]" /></a>{canSign && !document.signed && <Button type="button" size="sm" variant="outline" className="shrink-0 border-[#b18f4b] text-[#8a6b2d]" disabled={signPending} onClick={() => onSign(document.id)}><ShieldCheck className="mr-1.5 h-3.5 w-3.5" />Confirmar</Button>}</div>) : <p className="rounded-xl bg-[#faf8f3] p-4 text-sm text-muted-foreground">Nenhum documento anexado.</p>}</CardContent></Card>;
}
