import { EmptyState, PageHeader } from "@/components/crm/ui";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { AlertTriangle, CheckCircle2, CircleCheckBig, Download, FileSpreadsheet, LoaderCircle, Upload } from "lucide-react";
import { ChangeEvent, useMemo, useState } from "react";
import { toast } from "sonner";

type ImportKind = "customers" | "contracts";
type ImportStage = "idle" | "reading" | "ready" | "validating" | "review" | "validated" | "importing" | "done";
const templates: Record<ImportKind, string> = {
  customers: "nome_completo;documento;email;telefone;data_nascimento;estado_civil;profissao;cep;endereco;numero;complemento;bairro;cidade;uf;origem;status;observacoes\nAna da Silva;12345678900;ana@exemplo.com;17999999999;1985-07-25;Casada;Empresária;15400000;Rua das Flores;102;Apto 11;Centro;Olímpia;SP;Indicação;ativo;Prefere contato por WhatsApp",
  contracts: "numero_contrato;documento_associado;modelo_uso;status;valor_total;quantidade_parcelas;primeiro_vencimento;email_vendedor;observacoes\nTS-2026-0001;12345678900;semana_fixa;ativo;12500,00;12;2026-09-10;vendedor@empresa.com;Entrada paga no ato",
};
const stepLabels = ["Arquivo lido", "Validação concluída", "Gravação transacional", "Recibo final"];
const stepFor: Record<ImportStage, number> = { idle: 0, reading: 0, ready: 1, validating: 1, review: 2, validated: 2, importing: 3, done: 4 };

function downloadTemplate(kind: ImportKind) {
  const blob = new Blob([templates[kind]], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = kind === "customers" ? "modelo-associados.csv" : "modelo-contratos.csv"; anchor.click(); URL.revokeObjectURL(url);
}

export default function ImportCsv() {
  const { user } = useAuth(); const [kind, setKind] = useState<ImportKind>("customers"); const [fileName, setFileName] = useState(""); const [csv, setCsv] = useState(""); const [stage, setStage] = useState<ImportStage>("idle");
  const preview = trpc.imports.preview.useMutation({ onSuccess: data => setStage(data.valid ? "validated" : "review"), onError: error => { setStage("ready"); toast.error(error.message); } });
  const commit = trpc.imports.commit.useMutation({ onSuccess: result => { setStage(result.committed ? "done" : "review"); if (result.committed) toast.success(`Importação concluída: ${result.summary.successful} registro(s) aproveitado(s).`); else toast.error("O arquivo tem erros e nada foi gravado."); }, onError: error => { setStage("validated"); toast.error(error.message); } });
  const result = commit.data ?? preview.data; const summary = result?.summary; const sampleColumns = useMemo(() => result?.sample?.length ? Object.keys(result.sample[0] as object).slice(0, 6) : [], [result]);
  const step = stepFor[stage]; const active = stage !== "idle";
  const readFile = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; if (!file) return;
    if (!file.name.toLowerCase().endsWith(".csv") && file.type !== "text/csv") { toast.error("Envie um arquivo CSV."); return; }
    if (file.size > 2_000_000) { toast.error("O arquivo deve ter até 2 MB."); return; }
    setStage("reading"); const reader = new FileReader();
    reader.onload = () => { setCsv(String(reader.result ?? "")); setFileName(file.name); setStage("ready"); preview.reset(); commit.reset(); };
    reader.onerror = () => { setStage("idle"); toast.error("Não foi possível ler o arquivo."); }; reader.readAsText(file, "utf-8");
  };
  const inspect = () => { if (!csv.trim()) return toast.error("Escolha um CSV antes de validar."); setStage("validating"); preview.mutate({ kind, csv }); };
  const importRows = () => { if (!csv.trim()) return; setStage("importing"); commit.mutate({ kind, csv }); };
  if (user?.role !== "admin") return <EmptyState title="Importação restrita à administração" body="CSV muda cadastro, contrato e parcela em lote. Para não transformar a base numa panela de pressão, apenas Administração pode operar esta área." />;

  return <div className="space-y-8"><PageHeader eyebrow="Migração assistida" title="Importar associados & contratos" description="Suba o CSV, veja a prévia e só confirme quando cada linha estiver limpa. Aqui a planilha passa pela revista, não entra de capacete." action={<Button variant="outline" className="rounded-xl border-[#d9cfbd]" onClick={() => downloadTemplate(kind)}><Download className="mr-2 h-4 w-4" />Baixar modelo</Button>} />
    <div className="grid gap-5 xl:grid-cols-[1.05fr_1.95fr]"><Card className="rounded-[1.35rem] border-[#e9e4da]"><CardContent className="p-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#1d2b2a] text-[#e8d092]"><FileSpreadsheet className="h-5 w-5" /></div><h2 className="mt-4 font-serif text-2xl text-[#1d2b2a]">Preparar arquivo</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Associe os cabeçalhos ao modelo, escolha o tipo e rode a prévia. Nenhum dado é gravado nesta etapa.</p><div className="mt-6 grid gap-2"><Label>Conteúdo do arquivo</Label><Select value={kind} onValueChange={value => { setKind(value as ImportKind); preview.reset(); commit.reset(); setStage(csv ? "ready" : "idle"); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="customers">Associados</SelectItem><SelectItem value="contracts">Contratos & parcelas</SelectItem></SelectContent></Select></div><div className="mt-4 grid gap-2"><Label>Arquivo CSV</Label><Input type="file" accept=".csv,text/csv" onChange={readFile} /></div>{fileName ? <div className="mt-3 rounded-xl bg-[#faf8f3] p-3 text-sm text-[#1d2b2a]"><strong>{fileName}</strong><p className="mt-1 text-xs text-muted-foreground">{csv.split(/\r?\n/).filter(Boolean).length - 1} linha(s) de dados detectada(s).</p></div> : null}{active ? <div className="mt-4 rounded-xl border border-[#e7dfd0] bg-[#fbfaf7] p-3"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-[#1d2b2a]">{stage === "reading" ? "Lendo arquivo" : stage === "validating" ? "Validando regras" : stage === "importing" ? "Gravando em transação" : stage === "review" ? "Correção necessária" : stage === "done" ? "Processo concluído" : "Arquivo preparado"}</p><span className="text-xs text-muted-foreground">Etapa {Math.min(step, 4)} de 4</span></div><Progress value={Math.min(step, 4) * 25} className="mt-2 h-2 bg-[#e9e3d8] [&>div]:bg-[#1d5b53]" /><div className="mt-3 grid grid-cols-4 gap-1">{stepLabels.map((label, index) => <div key={label} className={`text-center text-[9px] leading-3 ${index < step ? "font-semibold text-[#285043]" : "text-muted-foreground"}`}>{label}</div>)}</div></div> : null}<Button onClick={inspect} disabled={!csv || preview.isPending || commit.isPending} className="mt-5 w-full bg-[#1d2b2a] hover:bg-[#29413e]"><Upload className="mr-2 h-4 w-4" />{preview.isPending ? "Validando..." : "Gerar prévia"}</Button><button className="mt-3 w-full text-xs font-semibold text-[#8a6b2d] hover:underline" onClick={() => downloadTemplate(kind)}>Baixar modelo de {kind === "customers" ? "associados" : "contratos"}</button></CardContent></Card>
      <Card className="rounded-[1.35rem] border-[#e9e4da]"><CardContent className="p-6">{!result ? <EmptyState title="A prévia aparece aqui" body="Envie um modelo preenchido e o sistema vai mostrar quantas linhas entram, o que está torto e uma amostra dos dados." /> : <div><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#b18f4b]">{result.committed ? "Recibo de importação" : "Resultado da validação"}</p><h2 className="mt-1 font-serif text-2xl text-[#1d2b2a]">{result.committed ? "Importação concluída" : result.valid ? "Arquivo pronto para entrar" : "Arquivo precisa de ajuste"}</h2><p className="mt-2 text-sm text-muted-foreground">{summary?.processed ?? result.totalRows} linha(s) analisada(s) · {summary?.rejected ?? 0} linha(s) rejeitada(s)</p></div>{result.valid || result.committed ? <Badge className="border-0 bg-[#e5efe4] text-[#24523e]"><CheckCircle2 className="mr-1 h-3.5 w-3.5" />{result.committed ? "Concluído" : "Validado"}</Badge> : <Badge className="border-0 bg-[#f9e8df] text-[#a54920]"><AlertTriangle className="mr-1 h-3.5 w-3.5" />Corrigir erros</Badge>}</div>
        {summary ? <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-xl bg-[#edf3ec] p-4"><CircleCheckBig className="h-4 w-4 text-[#285043]" /><p className="mt-2 text-2xl font-semibold text-[#1d2b2a]">{summary.created}</p><p className="text-xs text-[#285043]">criado(s)</p></div><div className="rounded-xl bg-[#f4efe2] p-4"><FileSpreadsheet className="h-4 w-4 text-[#8a6b2d]" /><p className="mt-2 text-2xl font-semibold text-[#1d2b2a]">{summary.updated}</p><p className="text-xs text-[#8a6b2d]">atualizado(s)</p></div><div className="rounded-xl bg-[#faf0ec] p-4"><AlertTriangle className="h-4 w-4 text-[#a54920]" /><p className="mt-2 text-2xl font-semibold text-[#1d2b2a]">{summary.rejected}</p><p className="text-xs text-[#a54920]">rejeitado(s)</p></div><div className="rounded-xl bg-[#faf8f3] p-4"><CheckCircle2 className="h-4 w-4 text-[#52615c]" /><p className="mt-2 text-2xl font-semibold text-[#1d2b2a]">{summary.processed}</p><p className="text-xs text-muted-foreground">processado(s)</p></div></div> : null}
        {summary?.issuesByField.length ? <div className="mt-5 rounded-xl border border-[#f0d9cc] bg-[#fffaf7] p-4"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#a54920]">Erros por categoria</p><div className="mt-3 flex flex-wrap gap-2">{summary.issuesByField.map(item => <Badge key={item.field} variant="outline" className="border-[#f0d9cc] bg-white text-[#8b4321]">{item.field}: {item.count}</Badge>)}</div></div> : null}
        {result.issues.length ? <div className="mt-6 overflow-hidden rounded-xl border border-[#f0d9cc]"><div className="grid grid-cols-[70px_140px_1fr] gap-3 bg-[#fff8f3] px-4 py-3 text-[10px] font-bold uppercase tracking-[.1em] text-[#a54920]"><span>Linha</span><span>Campo</span><span>Correção necessária</span></div>{result.issues.slice(0, 12).map((issue, index) => <div key={`${issue.line}-${issue.field}-${index}`} className="grid grid-cols-[70px_140px_1fr] gap-3 border-t border-[#f5e5dc] px-4 py-3 text-sm"><span>{issue.line}</span><span className="font-medium">{issue.field}</span><span className="text-muted-foreground">{issue.message}</span></div>)}</div> : null}
        {sampleColumns.length ? <div className="mt-6 overflow-x-auto"><p className="mb-3 text-[10px] font-bold uppercase tracking-[.12em] text-[#b18f4b]">Amostra de importação</p><table className="min-w-full text-left text-xs"><thead><tr className="border-b text-muted-foreground">{sampleColumns.map(column => <th key={column} className="px-3 py-2 font-semibold">{column}</th>)}</tr></thead><tbody>{result.sample.slice(0, 5).map((row, index) => <tr key={index} className="border-b border-[#f1ede5] text-[#1d2b2a]">{sampleColumns.map(column => <td key={column} className="max-w-44 truncate px-3 py-2">{String((row as Record<string, unknown>)[column] ?? "—")}</td>)}</tr>)}</tbody></table></div> : null}
        {result.valid && !result.committed ? <div className="mt-7 flex items-center justify-between gap-4 rounded-xl bg-[#edf3ec] p-4"><p className="text-sm leading-5 text-[#285043]">Tudo certo. Ao confirmar, associados serão criados/atualizados pelo documento; contratos criarão o cronograma de parcelas automaticamente.</p><Button onClick={importRows} disabled={commit.isPending} className="shrink-0 bg-[#1d2b2a] hover:bg-[#29413e]">{commit.isPending ? <><LoaderCircle className="mr-2 h-4 w-4 animate-spin" />Importando...</> : "Confirmar importação"}</Button></div> : null}</div>}</CardContent></Card></div></div>;
}
