import { PageHeader } from "@/components/crm/ui";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Save } from "lucide-react";
import { useEffect, useState } from "react";

export default function ProjectSettings() { const list = trpc.projectSettings.list.useQuery(); const utils = trpc.useUtils(); const [resortId, setResortId] = useState(""); const [form, setForm] = useState({ cancellationPolicy: "", requiredCaptureFields: "", commercialRoles: "", commissionPolicy: "" }); const selected = list.data?.find(x => String(x.resort.id) === resortId); useEffect(() => { if (!resortId && list.data?.[0]) setResortId(String(list.data[0].resort.id)); }, [list.data, resortId]); useEffect(() => { const s = selected?.settings; setForm({ cancellationPolicy: s?.cancellationPolicy || "", requiredCaptureFields: s?.requiredCaptureFields || "", commercialRoles: s?.commercialRoles || "", commissionPolicy: s?.commissionPolicy || "" }); }, [selected?.settings, resortId]); const save = trpc.projectSettings.upsert.useMutation({ onSuccess: () => utils.projectSettings.list.invalidate() }); return <div className="space-y-6"><PageHeader eyebrow="Administração" title="Regras por empreendimento" description="Cada projeto manda nas suas regras; o motor do TGR executa sem cirurgia de código." /><Card><CardContent className="space-y-5 p-6"><Select value={resortId} onValueChange={setResortId}><SelectTrigger><SelectValue placeholder="Selecione o empreendimento" /></SelectTrigger><SelectContent>{list.data?.map(x => <SelectItem key={x.resort.id} value={String(x.resort.id)}>{x.resort.name}</SelectItem>)}</SelectContent></Select>{([['cancellationPolicy','Distrato e multa'],['requiredCaptureFields','Campos obrigatórios da ficha'],['commercialRoles','Papéis: corretor, captador, liner, fechador'],['commissionPolicy','Divisão e calendário de comissão']] as const).map(([key,label]) => <div key={key}><p className="mb-2 text-sm font-semibold">{label}</p><Textarea value={form[key]} onChange={e => setForm(v => ({ ...v, [key]: e.target.value }))} placeholder="Defina a política deste empreendimento" /></div>)}<Button disabled={!resortId || save.isPending} onClick={() => save.mutate({ resortId: Number(resortId), ...form })}><Save className="mr-2 h-4 w-4" />Salvar regras do projeto</Button></CardContent></Card></div>; }
