import { useAuth } from "@/_core/hooks/useAuth";
import { EmptyState, PageHeader, money, StatusPill } from "@/components/crm/ui";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { useDebouncedValue } from "@/hooks/useDebouncedValue";
import { Award, CheckCircle2, ClipboardCheck, FileText, Plus, Target, TicketPercent } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const columns = ["new", "qualified", "proposal", "negotiation", "won"] as const;
const labels = { new: "Novas", qualified: "Qualificadas", proposal: "Propostas", negotiation: "Negociação", won: "Fechadas" };
const playbookStages = ["new", "qualified", "proposal", "negotiation", "won", "lost"] as const;
const playbookLabels = { ...labels, lost: "Perdidas" };

function DiscountDecisionDialog({ id, proposalReference }: { id: number; proposalReference: string }) {
  const [open, setOpen] = useState(false);
  const utils = trpc.useUtils();
  const decide = trpc.sales.decideDiscount.useMutation({
    onSuccess: () => { utils.sales.discountApprovals.invalidate(); setOpen(false); toast.success("Decisão de desconto registrada."); },
    onError: error => toast.error(error.message),
  });
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    decide.mutate({ id, approve: form.get("decision") === "approve", decisionNotes: String(form.get("notes") || "") || undefined });
  };
  return <Dialog open={open} onOpenChange={setOpen}>
    <DialogTrigger asChild><Button size="sm" variant="outline">Decidir</Button></DialogTrigger>
    <DialogContent>
      <DialogHeader><DialogTitle className="font-serif text-2xl">Decidir desconto · {proposalReference}</DialogTitle></DialogHeader>
      <form className="grid gap-4" onSubmit={submit}>
        <Textarea name="notes" placeholder="Observação da decisão (opcional)" />
        <div className="grid grid-cols-2 gap-3">
          <Button name="decision" value="reject" type="submit" variant="outline" disabled={decide.isPending}>Recusar</Button>
          <Button name="decision" value="approve" type="submit" className="bg-[#1d2b2a] hover:bg-[#29413e]" disabled={decide.isPending}>Aprovar</Button>
        </div>
      </form>
    </DialogContent>
  </Dialog>;
}

export default function Sales() {
  const { user } = useAuth();
  const [open, setOpen] = useState(false);
  const [proposalOpen, setProposalOpen] = useState(false);
  const [goalOpen, setGoalOpen] = useState(false);
  const [discountOpen, setDiscountOpen] = useState(false);
  const [playbookOpen, setPlaybookOpen] = useState(false);
  const [customerId, setCustomerId] = useState("");
  const [campaignId, setCampaignId] = useState("none");
  const [stage, setStage] = useState<(typeof columns)[number]>("new");
  const [opportunityId, setOpportunityId] = useState("");
  const [sellerId, setSellerId] = useState("");
  const [discountProposalId, setDiscountProposalId] = useState("");
  const [playbookStage, setPlaybookStage] = useState<(typeof playbookStages)[number]>("qualified");
  const [pipelineSearch, setPipelineSearch] = useState("");
  const [pipelineStage, setPipelineStage] = useState<"all" | (typeof columns)[number]>("all");
  const [pipelineSeller, setPipelineSeller] = useState("all");
  const debouncedPipelineSearch = useDebouncedValue(pipelineSearch);
  const utils = trpc.useUtils();
  const pipeline = trpc.sales.pipeline.useQuery({ ...(debouncedPipelineSearch ? { search: debouncedPipelineSearch } : {}), ...(pipelineStage !== "all" ? { stage: pipelineStage } : {}), ...(pipelineSeller !== "all" ? { sellerId: Number(pipelineSeller) } : {}), limit: 120 });
  const customers = trpc.customers.list.useQuery();
  const campaigns = trpc.campaigns.list.useQuery();
  const team = trpc.team.list.useQuery();
  const goals = trpc.sales.goals.useQuery();
  const quality = trpc.sales.qualityRanking.useQuery();
  const playbooks = trpc.sales.playbooks.useQuery();
  const proposals = trpc.sales.proposals.useQuery();
  const discountApprovals = trpc.sales.discountApprovals.useQuery(undefined, { enabled: user?.role === "admin" });
  const createOpportunity = trpc.sales.createOpportunity.useMutation({ onSuccess: () => { utils.sales.pipeline.invalidate(); setOpen(false); toast.success("Oportunidade criada."); }, onError: e => toast.error(e.message) });
  const updateOpportunity = trpc.sales.updateOpportunity.useMutation({ onSuccess: () => { utils.sales.pipeline.invalidate(); toast.success("Campanha atualizada."); }, onError: e => toast.error(e.message) });
  const createProposal = trpc.sales.createProposal.useMutation({ onSuccess: () => { utils.sales.pipeline.invalidate(); utils.sales.proposals.invalidate(); setProposalOpen(false); toast.success("Proposta registrada."); }, onError: e => toast.error(e.message) });
  const createGoal = trpc.sales.createGoal.useMutation({ onSuccess: () => { utils.sales.goals.invalidate(); setGoalOpen(false); toast.success("Meta salva."); }, onError: e => toast.error(e.message) });
  const createPlaybook = trpc.sales.createPlaybook.useMutation({ onSuccess: () => { utils.sales.playbooks.invalidate(); setPlaybookOpen(false); toast.success("Playbook comercial publicado."); }, onError: error => toast.error(error.message) });
  const createDiscount = trpc.sales.createDiscountRequest.useMutation({ onSuccess: data => { utils.sales.discountApprovals.invalidate(); setDiscountOpen(false); toast.success(`Pedido de desconto de ${data.discountPercent.toFixed(2)}% enviado para aprovação.`); }, onError: error => toast.error(error.message) });
  const submitOpportunity = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (!customerId) return toast.error("Selecione o cliente."); createOpportunity.mutate({ customerId: Number(customerId), campaignId: campaignId === "none" ? null : Number(campaignId), title: String(form.get("title")), expectedAmount: Number(form.get("amount")), source: String(form.get("source") || "") || null, stage }); };
  const submitProposal = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (!opportunityId) return toast.error("Selecione a oportunidade."); createProposal.mutate({ opportunityId: Number(opportunityId), reference: String(form.get("reference")), productDescription: String(form.get("description")), totalAmount: Number(form.get("amount")), downPaymentAmount: 0, installmentCount: 1, status: "sent" }); };
  const submitGoal = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (!sellerId) return toast.error("Selecione o vendedor."); createGoal.mutate({ sellerId: Number(sellerId), monthReference: String(form.get("month")), targetAmount: Number(form.get("amount")), targetContracts: Number(form.get("contracts") || 0) }); };
  const submitDiscount = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (!discountProposalId) return toast.error("Selecione a proposta."); createDiscount.mutate({ proposalId: Number(discountProposalId), requestedAmount: Number(form.get("requestedAmount")), rationale: String(form.get("rationale") || "") }); };
  const submitPlaybook = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); createPlaybook.mutate({ name: String(form.get("name") || ""), stage: playbookStage, guidance: String(form.get("guidance") || ""), checklist: String(form.get("checklist") || "") || null }); };

  return <div className="space-y-8">
    <PageHeader eyebrow="Comercial" title="Central de vendas" description="Funil, proposta, campanha e meta na mesma mesa — sem vendedor fazendo arqueologia no WhatsApp." action={<div className="flex flex-wrap gap-2">
      <Dialog open={goalOpen} onOpenChange={setGoalOpen}><DialogTrigger asChild><Button variant="outline"><Target className="mr-2 h-4 w-4" />Meta</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Definir meta</DialogTitle></DialogHeader><form className="grid gap-4" onSubmit={submitGoal}><Select value={sellerId} onValueChange={setSellerId}><SelectTrigger><SelectValue placeholder="Vendedor" /></SelectTrigger><SelectContent>{team.data?.filter(member => member.role === "seller" || member.role === "admin").map(member => <SelectItem key={member.id} value={String(member.id)}>{member.name || member.email}</SelectItem>)}</SelectContent></Select><Input name="month" type="date" required /><Input name="amount" type="number" min="1" placeholder="Meta em R$" required /><Input name="contracts" type="number" min="0" placeholder="Meta em contratos" /><Button type="submit">Salvar meta</Button></form></DialogContent></Dialog>
      <Dialog open={proposalOpen} onOpenChange={setProposalOpen}><DialogTrigger asChild><Button variant="outline"><FileText className="mr-2 h-4 w-4" />Proposta</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Nova proposta</DialogTitle></DialogHeader><form className="grid gap-4" onSubmit={submitProposal}><Select value={opportunityId} onValueChange={setOpportunityId}><SelectTrigger><SelectValue placeholder="Oportunidade" /></SelectTrigger><SelectContent>{pipeline.data?.filter(item => item.opportunity.stage !== "won").map(item => <SelectItem key={item.opportunity.id} value={String(item.opportunity.id)}>{item.customerName} · {item.opportunity.title}</SelectItem>)}</SelectContent></Select><Input name="reference" placeholder="PROP-2026-001" required /><Textarea name="description" placeholder="Condições comerciais" required /><Input name="amount" type="number" min="1" placeholder="Valor" required /><Button type="submit">Registrar proposta</Button></form></DialogContent></Dialog>
      {user?.role === "admin" ? <Dialog open={playbookOpen} onOpenChange={setPlaybookOpen}><DialogTrigger asChild><Button variant="outline"><ClipboardCheck className="mr-2 h-4 w-4" />Novo playbook</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle className="font-serif text-2xl">Novo playbook comercial</DialogTitle></DialogHeader><form className="grid gap-4" onSubmit={submitPlaybook}><div className="grid gap-2"><Label>Nome *</Label><Input name="name" placeholder="Ex.: Qualificação de tour" required /></div><div className="grid gap-2"><Label>Etapa *</Label><Select value={playbookStage} onValueChange={value => setPlaybookStage(value as typeof playbookStage)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{playbookStages.map(item => <SelectItem key={item} value={item}>{playbookLabels[item]}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Orientação *</Label><Textarea name="guidance" placeholder="O que o vendedor precisa obter, validar e registrar nesta etapa" minLength={10} required /></div><div className="grid gap-2"><Label>Checklist</Label><Textarea name="checklist" placeholder={"Uma ação por linha\nEx.: Confirmar renda e disponibilidade\nEx.: Registrar objeção principal"} /></div><Button type="submit" disabled={createPlaybook.isPending} className="bg-[#1d2b2a] hover:bg-[#29413e]">{createPlaybook.isPending ? "Publicando..." : "Publicar playbook"}</Button></form></DialogContent></Dialog> : null}
      <Dialog open={discountOpen} onOpenChange={setDiscountOpen}><DialogTrigger asChild><Button variant="outline"><TicketPercent className="mr-2 h-4 w-4" />Solicitar desconto</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle className="font-serif text-2xl">Pedido de desconto</DialogTitle></DialogHeader><form className="grid gap-4" onSubmit={submitDiscount}><div className="grid gap-2"><Label>Proposta *</Label><Select value={discountProposalId} onValueChange={setDiscountProposalId}><SelectTrigger><SelectValue placeholder="Selecione a proposta" /></SelectTrigger><SelectContent>{proposals.data?.filter(item => item.proposal.status !== "rejected" && item.proposal.status !== "expired").map(item => <SelectItem key={item.proposal.id} value={String(item.proposal.id)}>{item.proposal.reference} · {item.customerName} · original {money(item.proposal.totalAmount)}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Novo valor proposto *</Label><Input name="requestedAmount" type="number" min="0.01" step="0.01" placeholder="Valor menor que o original" required /></div><div className="grid gap-2"><Label>Justificativa *</Label><Textarea name="rationale" minLength={10} placeholder="Contexto, contrapartida e motivo comercial" required /></div><p className="rounded-xl bg-[#faf8f3] p-3 text-xs leading-5 text-muted-foreground">O sistema calcula o percentual e envia o pedido para decisão da administração. O vendedor não consegue se dar desconto escondido na moita.</p><Button type="submit" disabled={createDiscount.isPending} className="bg-[#1d2b2a] hover:bg-[#29413e]">{createDiscount.isPending ? "Enviando..." : "Enviar para aprovação"}</Button></form></DialogContent></Dialog>
      <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="bg-[#1d2b2a] hover:bg-[#29413e]"><Plus className="mr-2 h-4 w-4" />Nova oportunidade</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Abrir oportunidade</DialogTitle></DialogHeader><form className="grid gap-4" onSubmit={submitOpportunity}><Select value={customerId} onValueChange={setCustomerId}><SelectTrigger><SelectValue placeholder="Cliente" /></SelectTrigger><SelectContent>{customers.data?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.fullName}</SelectItem>)}</SelectContent></Select><Input name="title" placeholder="Oportunidade" required /><div className="grid grid-cols-2 gap-3"><Input name="amount" type="number" min="0" placeholder="Valor estimado" required /><Select value={stage} onValueChange={value => setStage(value as typeof stage)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{columns.slice(0, 4).map(item => <SelectItem key={item} value={item}>{labels[item]}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Campanha</Label><Select value={campaignId} onValueChange={setCampaignId}><SelectTrigger><SelectValue placeholder="Sem campanha" /></SelectTrigger><SelectContent><SelectItem value="none">Sem campanha</SelectItem>{campaigns.data?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.code} · {item.name}</SelectItem>)}</SelectContent></Select></div><Input name="source" placeholder="Origem: tour, indicação, evento..." /><Button type="submit">Criar oportunidade</Button></form></DialogContent></Dialog>
    </div>} />

    <section className="rounded-[1.35rem] border border-[#e9e4da] bg-white p-4 sm:p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#b18f4b]">Controle do funil</p><h2 className="mt-1 font-serif text-xl text-[#1d2b2a]">Cruzar vendedor, etapa e contexto</h2><p className="mt-1 text-sm text-muted-foreground">A busca corta o funil no servidor antes de desenhar os cartões.</p></div><div className="flex flex-wrap gap-3"><div className="grid min-w-56 gap-1"><Label htmlFor="pipeline-search">Busca</Label><Input id="pipeline-search" value={pipelineSearch} onChange={event => setPipelineSearch(event.target.value)} placeholder="Cliente, oportunidade ou origem" /></div><div className="grid min-w-44 gap-1"><Label htmlFor="pipeline-stage">Etapa</Label><Select value={pipelineStage} onValueChange={value => setPipelineStage(value as typeof pipelineStage)}><SelectTrigger id="pipeline-stage"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Todas as etapas</SelectItem>{columns.map(column => <SelectItem key={column} value={column}>{labels[column]}</SelectItem>)}</SelectContent></Select></div><div className="grid min-w-44 gap-1"><Label htmlFor="pipeline-seller">Vendedor</Label><Select value={pipelineSeller} onValueChange={setPipelineSeller}><SelectTrigger id="pipeline-seller"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Todos</SelectItem>{team.data?.filter(member => member.role === "seller" || member.role === "admin").map(member => <SelectItem key={member.id} value={String(member.id)}>{member.name || member.email}</SelectItem>)}</SelectContent></Select></div></div></div></section>
    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <Card className="overflow-hidden rounded-[1.35rem] border-[#e9e4da]"><CardContent className="p-0"><div className="flex items-center justify-between border-b border-[#eee9df] bg-[#faf8f3] px-6 py-4"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#b18f4b]">Playbooks por etapa</p><h2 className="mt-1 font-serif text-xl text-[#1d2b2a]">Roteiro que o time não pode pular</h2></div><ClipboardCheck className="h-5 w-5 text-[#b18f4b]" /></div>{playbooks.data?.length ? <div className="divide-y divide-[#f0ece4]">{playbooks.data.map(item => { const checklist = item.checklist?.split(/\r?\n|•/).map(step => step.trim()).filter(Boolean) ?? []; return <div key={item.id} className="px-6 py-4"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#e8efe8] px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-[#49645f]">{playbookLabels[item.stage as keyof typeof playbookLabels] ?? item.stage}</span><p className="font-semibold text-[#1d2b2a]">{item.name}</p></div><p className="mt-2 text-sm leading-6 text-[#4f615e]">{item.guidance}</p>{checklist.length ? <ul className="mt-3 grid gap-1.5 text-xs text-muted-foreground">{checklist.map((step, index) => <li key={`${item.id}-${index}`} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#b18f4b]" />{step}</li>)}</ul> : null}</div>; })}</div> : <div className="p-8 text-center text-sm text-muted-foreground">Nenhum playbook ativo. A regra existe no banco, mas o manual ainda não foi cadastrado.</div>}</CardContent></Card>
      <Card className="overflow-hidden rounded-[1.35rem] border-[#e9e4da]"><CardContent className="p-0"><div className="flex items-center justify-between border-b border-[#eee9df] bg-[#faf8f3] px-6 py-4"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#b18f4b]">Governança de desconto</p><h2 className="mt-1 font-serif text-xl text-[#1d2b2a]">Decisões em uma trilha só</h2></div><TicketPercent className="h-5 w-5 text-[#b18f4b]" /></div>{user?.role === "admin" ? <div className="divide-y divide-[#f0ece4]">{discountApprovals.data?.length ? discountApprovals.data.slice(0, 8).map(item => <div key={item.approval.id} className="flex flex-col gap-3 px-6 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-[#1d2b2a]">{item.proposalReference} · {money(item.approval.requestedAmount)}</p><p className="mt-1 text-xs text-muted-foreground">{item.requesterName || "Solicitante"} pediu {Number(item.approval.discountPercent).toFixed(2)}% · {item.approval.status}</p><p className="mt-1 text-xs text-[#4f615e]">{item.approval.rationale}</p></div>{item.approval.status === "pending" ? <DiscountDecisionDialog id={item.approval.id} proposalReference={item.proposalReference} /> : <StatusPill value={item.approval.status} />}</div>) : <div className="p-8 text-center text-sm text-muted-foreground">Nenhum pedido de desconto aguardando decisão.</div>}</div> : <div className="p-8 text-sm leading-6 text-muted-foreground">Envie o pedido pelo botão acima. A decisão fica reservada à administração e registrada na auditoria — capricho que evita cada promoção clandestina do caralho.</div>}</CardContent></Card>
    </section>

    {!pipeline.data?.length ? <EmptyState title="Nenhuma oportunidade aberta" body="Comece pelo próximo tour ou indicação — o funil não se alimenta sozinho." /> : <div className="grid gap-4 xl:grid-cols-5">{columns.map(column => <section key={column} className="min-h-72 rounded-2xl bg-[#f8f6f0] p-3"><p className="px-2 py-2 text-xs font-bold">{labels[column]}</p>{pipeline.data.filter(item => item.opportunity.stage === column).map(item => <Card key={item.opportunity.id} className="mb-3"><CardContent className="p-4"><StatusPill value={item.opportunity.stage} /><p className="mt-2 font-semibold">{item.opportunity.title}</p><p className="text-xs text-muted-foreground">{item.customerName}</p><p className="mt-3 font-serif">{money(item.opportunity.expectedAmount)}</p><Select value={item.opportunity.campaignId ? String(item.opportunity.campaignId) : "none"} onValueChange={value => updateOpportunity.mutate({ id: item.opportunity.id, data: { customerId: item.opportunity.customerId, sellerId: item.opportunity.sellerId, campaignId: value === "none" ? null : Number(value), title: item.opportunity.title, stage: item.opportunity.stage, source: item.opportunity.source, expectedAmount: Number(item.opportunity.expectedAmount), probability: item.opportunity.probability, nextFollowUpAt: item.opportunity.nextFollowUpAt?.toISOString() ?? null, lossReason: item.opportunity.lossReason } })}><SelectTrigger className="mt-3 h-8 text-xs"><SelectValue placeholder="Campanha" /></SelectTrigger><SelectContent><SelectItem value="none">Sem campanha</SelectItem>{campaigns.data?.map(campaign => <SelectItem key={campaign.id} value={String(campaign.id)}>{campaign.code} · {campaign.name}</SelectItem>)}</SelectContent></Select></CardContent></Card>)}</section>)}</div>}
    <section className="overflow-hidden rounded-[1.35rem] border border-[#e9e4da] bg-white"><div className="flex items-center justify-between border-b border-[#eee9df] bg-[#faf8f3] px-6 py-4"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#b18f4b]">Qualidade comercial</p><h2 className="mt-1 font-serif text-xl text-[#1d2b2a]">Ranking por evidência operacional</h2><p className="mt-1 text-sm text-muted-foreground">60% conversão de oportunidades resolvidas + 40% higiene de follow-up. Sem nota tirada do cu.</p></div><Award className="h-5 w-5 text-[#b18f4b]" /></div>{quality.data?.length ? <div>{quality.data.map((seller, index) => <div key={seller.sellerId} className="grid gap-3 border-b border-[#f0ece4] px-6 py-4 text-sm last:border-b-0 md:grid-cols-[auto_1.3fr_1fr_1fr_1fr]"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#e8efe8] text-xs font-bold text-[#49645f]">{index + 1}</span><div><p className="font-semibold text-[#1d2b2a]">{seller.sellerName}</p><p className="mt-1 text-xs text-muted-foreground">{seller.wonCount} ganhos · {seller.lostCount} perdidos · {seller.openCount} abertos</p></div><p><strong>{seller.qualityScore}</strong>/100<br /><span className="text-xs text-muted-foreground">Score de qualidade</span></p><p>{seller.conversionRate}%<br /><span className="text-xs text-muted-foreground">Conversão</span></p><p className={seller.overdueFollowUps ? "text-[#a64b1d]" : "text-[#2d675f]"}>{seller.followUpCompliance}%<br /><span className="text-xs text-muted-foreground">Follow-up · {seller.overdueFollowUps} vencidos</span></p></div>)}</div> : <div className="p-8 text-center text-sm text-muted-foreground">Ainda não há oportunidades atribuídas para calcular qualidade comercial.</div>}</section>
    <Card className="rounded-[1.35rem] border-[#e9e4da]"><CardContent className="p-6"><p className="text-xs font-bold uppercase text-[#b18f4b]">Metas em curso</p>{goals.data?.length ? goals.data.slice(0, 6).map(item => <p key={item.goal.id} className="mt-2 text-sm">{item.sellerName || "Vendedor"}: {money(item.currentAmount)} de {money(item.goal.targetAmount)} · {item.currentContracts}/{item.goal.targetContracts} contratos</p>) : <p className="mt-3 text-sm text-muted-foreground">Nenhuma meta cadastrada.</p>}</CardContent></Card>
  </div>;
}
