import { describe, expect, it } from "vitest";
import { borderoSummary, commissionAssignments, commissionDates, commissionStatus, releasedCommission, totalCommission } from "./commissionLifecycle";

describe("commission lifecycle", () => {
  it("calcula regra por papel e libera a comissão na proporção da entrada", () => { expect(totalCommission(100_000, "liner")).toBe(1910); expect(totalCommission(100_000, "closer")).toBe(1510); expect(totalCommission(100_000, "ftb")).toBe(3420); expect(releasedCommission(2_000, 8_000, 1_000)).toBe(250); });
  it("trata Front Back como papel único e não soma liner com fechador", () => { expect(commissionAssignments({ linerId: 9, closerId: 9 })).toEqual([{ userId: 9, role: "ftb" }]); expect(commissionAssignments({ linerId: 9, closerId: 12 })).toEqual([{ userId: 9, role: "liner" }, { userId: 12, role: "closer" }]); });
  it("fecha crédito no mês seguinte e aplica dias 7 e 25", () => { const dates = commissionDates("credit", new Date("2026-08-13T12:00:00Z")); expect(dates.closingAt.toISOString()).toContain("2026-09-30"); expect(dates.cancellationDeadlineAt.toISOString()).toContain("2026-10-07"); expect(dates.expectedPaymentAt.toISOString()).toContain("2026-10-25"); });
  it("prioriza pagamento, bloqueia cancelamento na janela e consolida borderô", () => { const dates = commissionDates("pix", new Date("2026-08-13T12:00:00Z")); const cancelled = commissionStatus({ compensatedAt: new Date("2026-08-13T12:00:00Z"), receivedAt: null, cancelledAt: new Date("2026-09-05T12:00:00Z"), ...dates, now: new Date("2026-09-06T12:00:00Z") }); const paid = commissionStatus({ compensatedAt: new Date("2026-08-13T12:00:00Z"), receivedAt: new Date("2026-09-25T12:00:00Z"), cancelledAt: null, ...dates, now: new Date("2026-09-25T12:00:00Z") }); expect(cancelled).toBe("cancelled"); expect(paid).toBe("paid"); expect(borderoSummary([{ amount: 100, status: cancelled, expectedPaymentAt: dates.expectedPaymentAt }, { amount: 50, status: paid, expectedPaymentAt: dates.expectedPaymentAt }])).toMatchObject({ expected: 150, cancelled: 100, paid: 50, installments: 2 }); });
});
